### ISSUE TITLE
The DiffProcessor Java documentation seems to have errors.

### ISSUE THREAD

**Issue by DichoMire** [cap-js/docs#1045]
Hi,

In this [documentation](https://cap.cloud.sap/docs/java/cds-data#diff-processor):

### There seems to be errors in the examples

There is an example where the oldImage is:

```
  [
    {
      "title": "Wuthering Heights",
      "editions": []
    },
    {
      "title": "Catweazle",
      "editions": []
    }
  ]
```

And the newImage:

```
  [
    {
    "title": "Wuthering Heights",
      "editions": [
        {
          "title": "Wuthering Heights: 100th Anniversary Edition"
        }
      ]
    },
    {
      "title": "Catweazle",
      "editions": [
        {
          "title": "Catweazle: Director's Cut"
        }
      ]
    }
  ]
  ```
  
  However, the explanation that follow states the same edition for both the first and second call of added():

<img width="475" alt="hmmma" src="https://github.com/cap-js/docs/assets/56360395/782b5fac-d7a1-4786-8605-c3277442bd9b">

When I would expect the second call to be:
```
          "title": "Catweazle: Director's Cut"
```

### There is a second issue a little bit further down:

<img width="488" alt="hmma2" src="https://github.com/cap-js/docs/assets/56360395/0706d165-af4b-4373-8bff-695964ac443a">

Where I'd expect the third one to be:
```
          "title": "Catweazle: Complete with Extras"
```

**Comment by vmikhailenko** [comment]
Fixed with https://github.com/cap-js/docs/issues/1045

The point was to illustrate that you always observe respective entity states (as a whole) or changed elements (one by one).
