### ISSUE TITLE
Typo in example code snippet provided for Bulk Insert

### ISSUE THREAD

**Issue by gvkamal-sap** [cap-js/docs#1096]
Hi Colleagues,
There's typo in the example code snippet provided for Bulk Insert, which is very minor issue. Please find below for more details.

Location:
[https://cap.cloud.sap/docs/java/working-with-cql/query-api#bulk-insert](https://cap.cloud.sap/docs/java/working-with-cql/query-api#bulk-insert)
[https://github.com/cap-js/docs/blob/1c8a2c04ba4ef038dfe8924beaafd9ce72ff7d60/java/working-with-cql/query-api.md?plain=1#L839](https://github.com/cap-js/docs/blob/1c8a2c04ba4ef038dfe8924beaafd9ce72ff7d60/java/working-with-cql/query-api.md?plain=1#L839)

<img width="1113" alt="image" src="https://github.com/cap-js/docs/assets/168080002/447839b5-4310-4571-a0fa-b498b9d1f6dc">

With Best Regards,
Phaneendra Kamal G V

**Comment by renejeglinsky** [comment]
Thank you @gvkamal-sap for opening this issue. Much appreciated! :)

**Comment by renejeglinsky** [comment]
Has been fixed with #1099 

Thanks again! :)
