### ISSUE TITLE
composition sample not fellowing DB normalfrom?

### ISSUE THREAD

**Issue by bvarwig** [cap-js/docs#1115]
The Capire docu at https://cap.cloud.sap/docs/cds/cdl#compositions provides this example: 

```
entity Orders {
  key ID: Integer; //...
  Items : Composition of many Orders.Items on Items.parent = $self;
}
entity Orders.Items {
  key pos : Integer;     
  key parent : Association to Orders;
  product : Association to Products;
  quantity : Integer;
}
```

In the above example, **pos** not only serves as part of the primary key but also has a meaningful semantic load, like indicating the order or sequence of items. 

I suggest renaming the pos to ID. I assume the position of the items are not realy relevant. 
If you think the order of items is relevant this would than end up in the below suggestion:
```
entity Orders {
  key ID: Integer; //...
  Items : Composition of many Orders.Items on Items.parent = $self;
}
entity Orders.Items {
  key ID : Integer;     
  key parent : Association to Orders;
  position: Integer;  //please decide if the position property of an item is relevant/needed for the example!
  product : Association to Products;
  quantity : Integer;
}
```

**Comment by smahati** [comment]
Hello,

Thank you for creating this issue, it was determined that the key can be named pos and will not be changed but, thank you for your suggestion.

Best regards,
Maha
