### ISSUE TITLE
Why do all the nodejs properties and methods of the cds object contain a space after the period?

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [cap-js/docs#1126]
I have been going through the nodejs docs for CDS and have noticed that the property and method names have a space after the period. This makes it a bit annoying to copy and causes a bit of noise, at least I feel that. Am I missing some good reason for doing this?

**Comment by smahati** [comment]
Hello,

Thank you for the feedback The spaces are added for readability reasons (in some places they are needed too). We appreciate the suggestion though!

Best regards,
Maha
