### ISSUE TITLE
Spelling mistake in tools/cds-cli.md

### ISSUE THREAD

**Issue by andrew-barnard** [cap-js/docs#1155]
The section Sample Records in the cds add documentation in tools/cds-cli.md contains a spelling mistake.

The current text is "Watch a short video by DJ Adams to see this in acion."
It text should read "Watch a short video by DJ Adams to sett this in action."

![SNAG-00000](https://github.com/user-attachments/assets/47da3f41-3b99-462c-acab-54fe2267427b)

**Comment by smahati** [comment]
Hello,

Thank you for reporting this issue!

**Comment by smahati** [comment]
Hello,

This has been changed on the deployed branch and will be seen on main when the two are synchronised.

Best regards,
Maha

**Comment by swaldmann** [comment]
Fixed on cap.cloud.sap:
https://cap.cloud.sap/docs/tools/cds-cli#sample-records
