### ISSUE TITLE
Are asynchronous responses supported?

### ISSUE THREAD

**Issue by horsemanjackyliu** [cap-js/docs#1156]
If I use the following method , the resposne is 'HTTP/1.1 204 No Content' .
This method is supported in Express . CDS.service also is supporte with Express . Why this method is not supported .   

```js
srv.on("render", DnItems, async function (req, next) {
        dnApi
            .run(req.query)
            .then((res) => {
                console.log(res);
                req.reply(res);
            })
            .catch((err) => {
                console.log(err);
                req.reply(err.message);
            });
    });
```

**Comment by horsemanjackyliu** [comment]
Of cource  we use await , it works,  but it should support async API call in a better way .

**Comment by smahati** [comment]
Hello,

Thank you for the feedback! I will check and let you know.

Best regards,
Maha

**Comment by smahati** [comment]
Hello @horsemanjackyliu ,

Could you share which method is not supported? An example or link to the method in express would be helpful.

Best regards,
Maha

**Comment by horsemanjackyliu** [comment]
Hi,  Maha,

The following methods is not supported in CAP .



`const {
    StoreFormsApi,
    ADSRenderRequestApi,
} = require("./external/generated/adsapi/CF_ADSRestAPI");
const cds = require("@sap/cds");

module.exports = cds.service.impl(async function (srv) {
srv.on("render", DnItems, async function (req, next) {
        dnApi
            .run(req.query)
            .then((res) => {
                console.log(res);
                req.reply(res);
            })
            .catch((err) => {
                console.log(err);
                req.reply(err.message);
            });
    });
}`



Similiar method is supported in Express .
https://community.sap.com/t5/technology-blogs-by-sap/build-digital-document-platform-backend-service-on-btp-with-btp-ads-sdm/ba-p/13575468





`const {ServiceApi} = require( './service');
const express = require('express');
const app = express();
const xsenv = require('@sap/xsenv');
const fs = require('fs');

const base64 = require('base64topdf');

xsenv.loadEnv();
const services = xsenv.getServices({
    uaa: { label: 'xsuaa' }
});

const xssec = require('@sap/xssec');
const passport = require('passport');
passport.use('JWT', new xssec.JWTStrategy(services.uaa));
app.use(passport.initialize());
app.use(passport.authenticate('JWT', {
    session: false
}));

app.use(express.urlencoded({ extended: true }));
app.use(express.json());

app.get('/srv', function (req, res) {
    if (req.authInfo.checkScope('$XSAPPNAME.User')) {
        res.status(200).send('adsUnify');
    } else {
        res.status(403).send('Forbidden');
    }
});

app.post('/srv/pdfplatform', function (req, res) {
    ServiceApi.render(req.body.render).then( pdf=>{
 if(req.body.sign){
    req.body.sign.pdf = pdf;
    ServiceApi.sign(req.body.sign).then(spdf=>{
        base64.base64Decode(spdf,'render.pdf');
        const content = fs.readFileSync('render.pdf');
        const blob = new Blob([content], {type: 'application/pdf'});

        if(req.body.email){ 
            ServiceApi.semail(content,req.body.email.attachname,req.body.email.sendto,req.body.email.subject,req.body.email.ebody).then((info=>{
                console.log('email sent successfully');
            })).catch(err=>{console.log(err)});
                 };   

        if(req.body.cmis){
            
            ServiceApi.createDoc(blob,req.body.cmis.name,req.body.cmis.path).then(cmisresp=>{
                console.log(cmisresp.succinctProperties);
            }).catch(err=>{
                console.log(err);
            });
                        };


        if(req.body.print){         
            // fs.close();
            ServiceApi.print(content, req.body.print).then(result=>{
                console.log('uploaded into print queue  ' + req.body.print.qname)
            }).catch(err=>{
                console.log(err);
            });
        };

            let raw =  fs.createReadStream('render.pdf');
            res.writeHead(200, 'ok');
            raw.pipe(res);
            fs.rm('render.pdf',()=>{
                console.log('file deleted successfully');
            });
        
      
    }).catch(err=>{
        console.log(err);
        res.status(500).send(err);
    });
 }else{
        base64.base64Decode(pdf,'render.pdf');
        const content = fs.readFileSync('render.pdf');

        if(req.body.print){         
            ServiceApi.print(content, req.body.print).then(result=>{
                console.log('uploaded into print queue  ' + req.body.print.qname)
            }).catch(err=>{
                console.log(err);
            });
        }
    
        if(req.body.cmis){
           
            const blob = new Blob([content], {type: 'application/pdf'});
            ServiceApi.createDoc(blob,req.body.cmis.name,req.body.cmis.path).then(cmisresp=>{
                console.log(cmisresp.succinctProperties);
            }).catch(err=>{
                console.log(err);
            })
                        };
        if(req.body.email){ 
            ServiceApi.semail(content,req.body.email.attachname,req.body.email.sendto,req.body.email.subject,req.body.email.ebody).then((info=>{
                console.log('email sent successfully');
            })).catch(err=>{console.log(err)});
                 };     
        let raw =  fs.createReadStream('render.pdf');
        res.writeHead(200, 'ok');
        raw.pipe(res);
        fs.rm('render.pdf',()=>{
            console.log('file deleted successfully');
        });
 }       
    }).catch(err=>{
        console.log(err);
        res.status(500).send(err);
    });
    
});

app.get('/srv/user', function (req, res) {
    if (req.authInfo.checkScope('$XSAPPNAME.User')) {
        res.status(200).json(req.user);
    } else {
        res.status(403).send('Forbidden');
    }
});
const port = process.env.PORT || 5001;
app.listen(port, function () {
    console.info('Listening on http://localhost:' + port);
});`



Best regards!

Jacky Liu

**Comment by chgeo** [comment]
@horsemanjackyliu I am afraid we still guessing what you mean by 'this method'.  Can you be more precise?  Neither the link to the big blog post nor the lengthy code snippet help.

So, is it maybe a method on a request or a response object that you miss and that express provides?  If yes, clearly indicate which one.

**Comment by horsemanjackyliu** [comment]
What I mean is  CAP support await , but CAP does not support promise or Call back in Custom logic . But Express support await and promist both . But I read the following document, it seems it is reasonable .

https://runkit.com/docs/await

**Comment by smahati** [comment]
Hello @horsemanjackyliu ,

Please provide a minimal example, ideally similar to the short code block. Being able to reproduce the issue would help us to support you further.

Best regards,
Maha

**Comment by horsemanjackyliu** [comment]
No offense . If you have used CAP nodejs to realize some functions, you should already know what I mean . If you have not used CAP in Nodejs to build some real project. It is too hard for me to explain. Please close the issue .

**Comment by chgeo** [comment]
No offense.  I think I now know what you mean, but I understand it might be hard for you to explain.  Please follow my comment below and see how things can be phrased in a crisp yet understandable way (I hope).

So, this is working in Express, i.e. you are able to send a response asynchronously w/o returning or awaiting Promises:

```js
  app.use('/hello', (req, res) => {
    setTimeout(() => { res.send('Hello World!') }, 1000)
    //> ✅ returns 200 OK w/ 'Hello World!'
  })
```

While similar code in CAP Node.js does not work ootb:
```js
  this.on('func', req => {
    setTimeout(() => req.reply('Hello World!'), 1000)
    //> ❌ returns 204 No Content
  })
```

Here, you would have to return or await a Promise:
```js
  this.on('func', req => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(req.reply('Hello World!')), 1000)
    })
    //> ✅ returns 200 OK w/ 'Hello World!' 
  })
```

and must not forget to return (or await) it:
```js
  this.on('func', req => {
    new Promise((resolve) => {
      setTimeout(() => resolve(req.reply('Hello World!')), 1000)
    })
    //> ❌ forgot to return the promise
  })
```

Now to the experts @sjvans @David-Kunz @johannes-vogel : I guess this is expected/intended as responses are 'auto-closed' I guess?  Express seems to leave them open.  Any plans we want to change or make this possible?

**Comment by horsemanjackyliu** [comment]
Hi,Chgeo,
Thank you so much for your suggestion!
Based on your suggestion, I adjust the code as the following and it works . If this method is available in capire, it would help a lot of customers .


    srv.on("testRender", "DnItems", function (req, next) {
        return new Promise(resolve=>{
            cds.connect.to("API_OUTBOUND_DELIVERY_SRV_0002").then(dnApi=>{
                dnApi.run(req.query).then(dnItem=>{
                    resolve(req.reply(dnItem.DeliveryDocument))
                })
            });
        })

It works .

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/2e4650c7-9d7b-4342-9e61-09603d4c9dce">

**Comment by sjvans** [comment]
hi @horsemanjackyliu 

the design of express middleware and service handlers in CAP is fundamentally different. the former relies on explicitly calling the next callback to proceed, whereas the latter checks what the function returns (see [srv.on(request)](https://cap.cloud.sap/docs/node.js/core-services#srv-on-request)). [req.reply(<result>)](https://cap.cloud.sap/docs/node.js/events#req-reply) is basically syntactical sugar. you can simply return the result or the promise that resolves with the result.

there are no plans for changing this.

btw, you can also write your code as follows:
```js
srv.on("testRender", "DnItems", async function (req, _next) {
    const dnApi = await cds.connect.to("API_OUTBOUND_DELIVERY_SRV_0002")
    const dnItem = await dnApi.run(req.query)
    return dnItem.DeliveryDocument // or "req.reply(dnItem.DeliveryDocument)" with or without the return
})
```

best,
sebastian

**Comment by horsemanjackyliu** [comment]
Hi,  sebastian,

When I failed to use callback method as express . i used method await and it succeed .But I have some concern in performance in using  method Await . But i checked some documents and it seems the method await and callback method will have the same performance . So it seems we can use both methods .


Best regards!

Jacky Liu

**Comment by chgeo** [comment]
Glad to hear this is resolved.
@sjvans can you check our docs whether this question, i.e. the diff to express, is mentioned somewhere, and if not, add a section?  Could also be in the troubleshooting page.

**Comment by sjvans** [comment]
will bring it to the backlog
