### ISSUE TITLE
Using PostgreSQL cds build is not enough

### ISSUE THREAD

**Issue by Backo123** [cap-js/docs#1189]
Hello,

In the Using PostgreSQL guide, section [With a Deployer App](https://github.com/cap-js/docs/blob/main/guides/databases-postgres.md#with-a-deployer-app), it is suggested that the deployer app will be generated simply by executing:
`cds build`. 
While following the guide and executing the command, it doesn't generate a deployer app. After a lot of trial and error, my team found out that actually we need to execute:
`cds build --for postgres`

Can you please confirm and update the guide accordingly.

Cheers
Vassil Kossev

**Comment by smahati** [comment]
Hello,

This has been changed on the deployed branch and will be seen on main when the two are synchronised.

Best regards,
Maha
