### ISSUE TITLE
Spelling mistake in docs/guides/domain-modeling.md

### ISSUE THREAD

**Issue by julesdecock** [cap-js/docs#1204]
Hello,

The section "Fiori Annotations" in the "Domain Modeling" documentation contains a spelling mistake.

Current text states: "... starting with `@title`s used for field or ..."
I believe the s after `@title` is not needed in this case.

Screenshot of the current text:
![image](https://github.com/user-attachments/assets/db25c485-7a1a-45d1-8051-e42cddaf5891)

**Comment by smahati** [comment]
Hi,

Thank you for reaching out, at first glance I think it's there to indicate that there are numerous instances of each annotation but I'll check and update it as needed.

Best regards,
Mahati

**Comment by smahati** [comment]
Hello,

I updated it in this commit: https://github.com/cap-js/docs/commit/3a83227b9d996e5d3da00e3900831d66d72f7ec2 .
Thank you for helping us by reporting the issue.

Best regards,
Mahati

**Comment by smahati** [comment]
Hello,

I'll close this issue as the mistake was fixed, please create another issue if you need to report anything else. Thanks!

Best regards,
Mahati
