### ISSUE TITLE
Token of service XSUAA removed from SecurityContext (thread-locally)

### ISSUE THREAD

**Issue by horsemanjackyliu** [cap-js/docs#1240]
I deployed a MTA application with UI5 as the front end CAP JAVA as the backend. At the begin the UI5 app works, but suddenly the UI5 applicaton does not work .

I checked the backend logs . The issue is due to the following log:
2024-09-09T08:47:49.736+0000 [APP/PROC/WEB/0] STDOUT 2024-09-09T08:47:49.736Z DEBUG 7 --- [nio-8080-exec-2] c.s.c.security.token.SecurityContext     : Token of service XSUAA removed from SecurityContext (thread-locally).

The whole project is in https://github.com/horsemanjackyliu/labelprintinginjava .

The logs are in the attachment. This issue exists in CAP NodeJs adn CAP JAVA both .Would you please help with high priority on this ?

[caplabelprinting1-srv-2024-09-09 09_21_48.785+0000.txt](https://github.com/user-attachments/files/16928656/caplabelprinting1-srv-2024-09-09.09_21_48.785%2B0000.txt)

**Comment by chgeo** [comment]
This is a regular issue, not a documentation issue. Open it on our internal issue channel. 

Thanks
