### ISSUE TITLE
Error in app-specific cds.env?

### ISSUE THREAD

**Issue by bkrencker** [cap-js/docs#1283]
Hi

The documentation about App-Specific Settings in cds.env is wrong. The example shown here is not working (on CDS v8).

https://github.com/cap-js/docs/blob/b85a1087d4f1361c880e510cdc68145252e8fdce/node.js/cds-env.md?plain=1#L439-L454

Best regards,
Ben

**Comment by renejeglinsky** [comment]
Hi @bkrencker ,
thanks a lot for opening the issue. I'm happy to dig into it. Could you provide some more information about the error you're facing, what you wanted to configure,... That helps me getting the right support for this issue quicker. Thank you!

**Comment by bkrencker** [comment]
Hi @renejeglinsky 
Yes sure, what is not working is accessing the variable by `cds.env.for('my-app')`. Using `for()` I believe is when working with profiles like hybrid, production, development and so on. But here in this example I believe the correct syntax would be `cds.env.my-app.myoption`..?
Best regards,
Ben

**Comment by renejeglinsky** [comment]
Hi @johannes-vogel ,
could you please check this issue?
Best,
René

**Comment by johannes-vogel** [comment]
I'm not an expert on this.
I can see that `cds.env['my-app']` contains the correct value.

@chgeo Do you have an idea?

**Comment by chgeo** [comment]
Just tested it and works just fine as documented, also with cds 8.

Given this config:
```jsonc
{ 
  "myapp": {
    "key": true
  }
}
```

I ran this:

```
» cds r
Welcome to cds repl 
> cds.env.for('myapp')
Config {
  _context: 'myapp',
  _home: '/private/tmp/envtest',
  _sources: [ '/private/tmp/envtest/package.json', 'process.env' ],
  _profiles: Set(1) { 'development', _defined: Set(0) {} },
  key: true
}
> cds.env.for('myapp').key
true
> cds.env.myapp
```

Was also discussed (and fixed) in https://github.com/cap-js/docs/pull/120.

**Comment by bkrencker** [comment]
I am running on CDS 8 (8.2.3) and used the config as shown in the documentation.

When running locally with `cds watch --profile hybrid` the value was not read using `cds.env.for('my-app')`.

Then I switched to `cds.env.my-app.myoption`, this war working fine. I guess that also `cds.env['my-app'].myoption` would work.

**Comment by chgeo** [comment]
@bkrencker Please check that you didn't add the `my-app` key below `cds` by mistake.  This would explain the behavior.

**Comment by bkrencker** [comment]
Yes I believe this is what I did following the example in the docs:

 ```json [package.json] 
 "cds": { ... }, 
 "my-app": { "myoption": "value" } 
 ```

**Comment by chgeo** [comment]
No, I meant having the key _inside_ the `cds` block would cause the issue. This is not what you seem to have done though. 

Anyway, please create a minimal example project so that I can reproduce the issue.

**Comment by bkrencker** [comment]
Yeah you are right, sorry for that! I accidently put the key inside the cds block.. 😲
