### ISSUE TITLE
Issue with Additionnal fields in projection when using @sap/cds version 8 (works with @sap/cds version 7)

### ISSUE THREAD

**Issue by laurent-duplat-tw** [cap-js/docs#1340]
Hello,

I recently switch from @sap/cds version 7 to version 8 on an old project.

In this project, I use an external service with an entity "MyEntityFromExternalService" and I add some additionnal fields like this:

```
@cds.persistence.skip: true
    @cds.persistence.table
    entity MyEntityExtended        as
        projection on my.MyEntityFromExternalService {
            *,
            ''          as AdditionnalField              : String
        }
```

I defined also an action using "MyEntityExtended":

`action   doSomething(myData: MyEntityExtended)  returns SomeStuff;`

When I call "doSomething" using a payload including field AdditionnalField, "req.data.myData.AdditionnalField" is empty (only with @sap/cds version 8 and it works with version 7).

Is it a bug with version 8 ? or Did something change in the way of doing it ?

Thank you.

**Comment by renejeglinsky** [comment]
Hi @laurent-duplat-tw ,
in this repository we only handle issue related to documentation. You can reach our Dev experts either creating a support ticket or asking in the [community](https://community.sap.com/t5/c-khhcw49343/SAP+Cloud+Application+Programming+Model/pd-p/9f13aee1-834c-4105-8e43-ee442775e5ce). The latter would be the preferred way, as this way also others can find it and benefit from everything that is done and found out.
If you find that there's sth missing/wrong in the documentation, please reopen this issue.

Thanks and all the best,
René
