### ISSUE TITLE
Migration to CAP8 - Missing Implementation - JS/TS-Files are not bound to Service - Workaround

### ISSUE THREAD

**Issue by Markus-Schroeder-de** [cap-js/docs#1375]
After Migration a Project to CAP8 we missed the implementation. As you know, you have for the Service a .cds-File (for example TestService.cds). If the Application starts, it searched for the corresponding Implementation, a File like TestService.js or TestService.js. This works fine in the local development and also in the BTP with Version < 8.

But after migration to CAP8 and deployment to the BTP this didn't work as expected. In the local dev-enviroment (devcontainer and using "cds-ts watch") everything works as expected.

I set up a Testproject and there it works after deployment to the BTP as expected without any changes.

I am not shure why it works with the Testproject and not in the real project. I suspect that it may be due to the existing cdsrc.json in the real project.

I could solve it as a Workaround, adding "@impl: 'TestService.js' to the TestService.cds (even if it is a Typescript-Project you have to choose .js as Filedescriptor!)

After that the implementation in the BTP works, but the project did not run anymore in the local dev enviroment, because it can't find the TestService.js for the implementation, because it's only exist to runtime and not while using cds-ts watch.

I think this is a bug. s

**Comment by Markus-Schroeder-de** [comment]
wrong git-project, sry.

**Comment by Markus-Schroeder-de** [comment]
wrong project, sry.

**Comment by renejeglinsky** [comment]
Hi Markus,
as you already found, this repository is not meant for bug reports. I've seen that you also used discussions here on GitHub. But I'd like to point you to our official channels, which you can also find on this page: https://cap.cloud.sap/docs/resources/#public-resources
![image](https://github.com/user-attachments/assets/7b7d2f72-4df2-42e4-8376-32bcf6c2f8fe)
