### ISSUE TITLE
Menu does not reflect the plugin page correctly, correct Websocket writing

### ISSUE THREAD

**Issue by oklemenz2** [cap-js/docs#1414]
In menu, still **OData V2 Proxy** instead of **OData V2 Adapter** is mentioned. Furthermore the entry `Websocket` is missing. 

<img width="1171" alt="Bildschirmfoto 2024-11-04 um 11 35 36" src="https://github.com/user-attachments/assets/1f79870f-c338-4f62-80d5-14385d364dd7">

In addition, Websocket should be written like this `WebSocket` ...

**Comment by renejeglinsky** [comment]
Thanks Oliver! I'm on it.
