### ISSUE TITLE
custom fields in CLS

### ISSUE THREAD

**Issue by qby-ankul** [cap-js/docs#1424]
Hi all,

I am trying to define my own fields in CLS. For the ALS it works as described, even if the documentation here is a bit thin. How do I have to pass the parameters to the logger? In ALS I pass them as an object, this does not work in CLS.

https://github.com/cap-js/docs/blob/894f95df02e550a3a8379202d473b59a8678abba/node.js/cds-log.md?plain=1#L406

**Comment by renejeglinsky** [comment]
Hi @qby-ankul,
just to clarify: CLS is SAP Cloud Logging Service and ALS is SAP Application Logging Service. Correct?

So the section you've linked contains information for both services. If I understand correctly, you experience that the docs for ALS are correct (even if they're thin) but for CLS the docs are incorrect and don't enable you to make it work. Right?

Could you give an example configuration that doesn't work? Is there an error message or sth alike that you can share?

**Comment by qby-ankul** [comment]
Hi @renejeglinsky,

Yes, that's right.

We used the following code in ALS:
`cds.log("logger").info(value, {"custom_field": field_value});`

Which no longer works in CLS. In general, I would like the documentation to be more meaningful than how do I configure this. But also, how can I use it.

**Comment by renejeglinsky** [comment]
Thanks @qby-ankul. So you're trying to use the same custom field in both, ALS and CLS, correct? I'm not sure if this is possible.

@sjvans Could you give some insights here?

**Comment by qby-ankul** [comment]
Hi @renejeglinsky,

no, we switched from ALS to CLS. So far we have lived with it being displayed in msg. However, this is not a permanent solution. We would like it to be listed as a separate field as mentioned in the documentation or in ALS.

**Comment by sjvans** [comment]
hi @qby-ankul 

could you please elaborate on "this does not work in CLS"?

for me, it works no problem:

```json
"cds": {
  "log": {
    "als_custom_fields": {
      "bla": 0
    },
    "cls_custom_fields": [
      "bla"
    ]
  }
}
```

```js
const cds = require('@sap/cds')
const LOG = cds.log('foo')

module.exports = srv => {
  srv.on('bar', req => {
    LOG.info('baz', { bla: 'blub' })
  })
}
```

ALS:
![Screenshot 2024-11-07 at 13 32 37](https://github.com/user-attachments/assets/82480b82-b3df-42e7-9921-87e04cd0f366)

CLS:
![Screenshot 2024-11-07 at 13 32 46](https://github.com/user-attachments/assets/52940aa1-b9f2-476d-bcb0-1efa3776b3ea)

best,
sebastian

**Comment by qby-ankul** [comment]
Hi @sjvans 

unfortunately does not work for me: https://github.com/qby-ankul/cls-custom-fields-demo/blob/main/cls-log.json

 I have created an example: https://github.com/qby-ankul/cls-custom-fields-demo/tree/main

The CLS is set up according to the documentation: Bind the Application to a User Provided Service
https://help.sap.com/docs/cloud-logging/cloud-logging/ingest-via-cloud-foundry-runtime?locale=en-US&version=Cloud

**Comment by sjvans** [comment]
hi @qby-ankul 

the binding via user-provided service is the issue. we assume a "normal" binding that identifies the service. otherwise we can not reliably protect against false positives... but i'll see what we can do.

can confirm the broken readiness checks, but i'll need to reach out to the respective colleagues. as far as i can tell, we generate an mta that is compliant to the [readiness-health-check-http-endpoint docs](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#readiness-health-check-http-ep).

best,
sebastian

**Comment by sjvans** [comment]
> bonus bug, the generated readiness parameters doesn't work ...

i created an issue/ feature request: https://github.com/SAP/cloud-mta-build-tool/issues/1147

**Comment by sjvans** [comment]
> the binding via user-provided service is the issue. we assume a "normal" binding that identifies the service. otherwise we can not reliably protect against false positives... but i'll see what we can do.

→ https://github.com/cap-js/docs/pull/1441

**Comment by qby-ankul** [comment]
Thank you for your great support @sjvans !

I have one suggestion for improvement, can the logging section be adapted to your example above?

Best regards 
Andre
