### ISSUE TITLE
Outdated `audit-logging` config example leads to an error

### ISSUE THREAD

**Issue by grenik** [cap-js/docs#1442]
The following config is outdated and leads to a "Module not found" error:
https://github.com/cap-js/docs/blob/aab041d8b70eede4af5dddd394208eaa56ece4e3/guides/data-privacy/audit-logging.md?plain=1#L495

Should be:
```js
"kind": "audit-log-to-console",
```

See the audit logging plugin [impl](https://github.com/cap-js/audit-logging/blob/9bbb1b1f370e00e39559a3507c7cb091bcfff8af/package.json#L45)

Tested locally in hybrid mode

**Comment by renejeglinsky** [comment]
Thanks a lot for opening this issue. The relevant docs have been improved based on your contribution. Thanks so much!
