### ISSUE TITLE
Typo on PostgreSQL documentation page 'automatic schema evolution' settings description.

### ISSUE THREAD

**Issue by ozgurkadir** [cap-js/docs#283]
Hello,

There might be a small typo in the **PostgreSQL** documentation page  like :

You can _switch of_ automatic schema evolution -> You can _switch off_ automatic schema evolution

Just an '**f**' is missing.

https://cap.cloud.sap/docs/guides/databases-postgres

**Comment by renejeglinsky** [comment]
Thanks @ozgurkadir ! I fixed the typo in the referenced PR. :)

All the best,
René
