### ISSUE TITLE
GitHub Icon Link points to SAP internal GitHub

### ISSUE THREAD

**Issue by gregorwolf** [cap-js/docs#291]
Hello,

right now the GitHub Icon Link in the upper right corner of Capire:

![Screenshot 2023-07-11 at 16 47 27](https://github.com/cap-js/docs/assets/2639535/76d423e6-c945-4441-b778-93b9182628ab)

points to https://github.tools.sap/cap which is SAP internal. I think it needs to be updated to https://github.com/cap-js/docs/.

CU
Gregor

**Comment by chgeo** [comment]
Thanks, fixed on the SAP side.
Will be published w/ the next patch this week or so.
