### ISSUE TITLE
Duplicate documentation for custom service implementation?

### ISSUE THREAD

**Issue by gregorwolf** [cap-js/docs#293]
Hi,

This morning I was searching for some guidance for the custom service implementation and found:

https://cap.cloud.sap/docs/node.js/services#srv-impl-how

which shows the 3 options (subclass, plain function, arrow function) as equal. But this afternoon I've navigated via https://cap.cloud.sap/docs/node.js/ and found:

https://cap.cloud.sap/docs/node.js/core-services#how-to-provide-custom-service-implementations

where the subclass based implementation has the preference. I think /docs/node.js/services is an artefact that should be checked for removal or?

Best Regards
Gregor

**Comment by renejeglinsky** [comment]
Hi @johannes-vogel and @danjoa ,

I think Gregor is totally right. Pls check and let me know or remove it yourself. Thanks!

All the best,
René
