### ISSUE TITLE
Links with anchor do not lead to correct section

### ISSUE THREAD

**Issue by patricebender** [cap-js/docs#296]
for example <https://cap.cloud.sap/docs/guides/databases#native-db-queries> does not lead me to the `native-db-queries` section, but to a section which is below the desired one. Tested on the newest Chrome Version as well as in Safari.

**Comment by renejeglinsky** [comment]
We know about a little issue with anchor links, but this offset is quite huge.

@swaldmann Could pls check this? Thanks a lot!

**Comment by chgeo** [comment]
Reported here: cap/issues#13650 → subscribe there
