### ISSUE TITLE
Problemn in configuration Pool - @cap-js/postgres

### ISSUE THREAD

**Issue by YoshiakiToma** [cap-js/docs#308]
In a follow file:
lib -> PostgresService.js

In the file above I having a problem with timeout millis in a pools config. So, when I try to deploy to any database Postgress, it has show timed out error.

![image](https://github.com/cap-js/docs/assets/31498873/b6f1d858-ac0e-4c88-961c-254510777db0)

This error occurr when I try to pass the config in Pool, doesn't work correctly because in the config in PostgresService.js has a fix config.
![image](https://github.com/cap-js/docs/assets/31498873/509c9ea5-4a55-4df5-a2a7-8d549cc1327c)

![image](https://github.com/cap-js/docs/assets/31498873/7cd661b6-b36e-4dd1-bc7e-9eff0f6cab6b)

If you see in the picture above, the problem is origin in fix values.

Is it possible to config when the parameters: acquireTimeoutMillis and destroyTimeoutMillis is null in the custom config, fix value 1000?

Regards

**Comment by gregorwolf** [comment]
Hi @YoshiakiToma,

please note that this is the repository for the CAP Documentation (Capire). Please file your incident in https://github.com/cap-js/cds-dbs and you're very welcome to provide a pull request which fixes this problem. Right now it seems we do not even make use of the [Pool](https://node-postgres.com/apis/pool) but instead we just instantiate a pg Client.

Best Regards
Gregor

**Comment by YoshiakiToma** [comment]
Thanks @gregorwolf , I'm going to open a PR with Fix for this problm.
