### ISSUE TITLE
Missing Release Notes for December 2022

### ISSUE THREAD

**Issue by IcyT** [cap-js/docs#311]
I just landed on the release notes for december 2022 by using the search function, but the release notes page is empty.

Here is a screenshot of my search, showing results for it:
![image](https://github.com/cap-js/docs/assets/783706/c73ec00d-841e-4526-bc91-0edd9314a1a0)

All the other months in 2022 have content.

**Comment by renejeglinsky** [comment]
Hi @IcyT ,

Thanks for reporting! I'm working on this one as well. It will get published in one go with #312.

All the best,
René

**Comment by renejeglinsky** [comment]
Me again :)

Just checked that the page is available: https://cap.cloud.sap/docs/releases/archive/2022/dec22
For you too?

**Comment by swaldmann** [comment]
Closing as completed as this seems to be working now:
https://cap.cloud.sap/docs/releases/archive/2022/dec22#csrf-token-handling-for-remote-services

Let us know if there are still problems on your side.
