### ISSUE TITLE
Release Notes of 2020 not available

### ISSUE THREAD

**Issue by IcyT** [cap-js/docs#312]
The release notes of 2020 are wrongly listed within "All of 2021".
In addition, each of them doesn't exist, resulting in a 404 error.

**Comment by renejeglinsky** [comment]
Hi @IcyT ,

Thanks for reporting! I'm working on it. Will let you know when this is fixed.

All the best,
René

**Comment by renejeglinsky** [comment]
Hi @IcyT ,

the release notes from 2020 are now available: https://cap.cloud.sap/docs/releases/archive/2020/

Thanks and all the best,
René
