### ISSUE TITLE
Errors deploying bookshop app

### ISSUE THREAD

**Issue by sfdfklskldf** [cap-js/docs#358]
I noticed several issues during deployment of the bookshop app example.
I used "jump start" from here: https://cap.cloud.sap/docs/guides/multitenancy/

1) Issue in ``mta.yaml``: ``xsappname: bookshop-${org}-${space}``
The ``${org}`` parameter fails if the name of the org contains spaces.
This is at least the case in "https://api.cf.us10.hana.ondemand.com"
Last year I also noticed that issue on EU10!
This can be fixed by some hard coded value

2) after deployment I get several errors - no idea what is missing:
a) in bookshop-mtx.log:
```
  cds.error(_errorMessage(e, 'acquiring', tenant), { status: e.response?.status ?? 500 }) (STDERR, APP/PROC/WEB)#
  ...
  Error: Error acquiring tenant t0: unknown error (STDERR, APP/PROC/WEB)#
```
b) in bookshop-srv.log
```
 throw new Error( (STDERR, APP/PROC/WEB)#
...
Error: Neither "hdb" nor "@sap/hana-client" could be required. Please make sure one of them is installed. (STDERR, APP/PROC/WEB)#
```

Should the example work out of the box? If so, what could be the reason for the errors?
If not, what must be changed?

**Comment by sfdfklskldf** [comment]
And by the way:
"Neither "hdb" nor "@sap/hana-client" could be required. Please make sure one of them is installed" 
In other words:
"Non of the mentioned packages are required but please install at least one."
Sounds somehow wrong?

In my case "@sap/hana-client" is in each package.json - just to be sure. :)

I also added 
cds add hana,xsuaa,approuter --for production

I have "SAP HANA Clodu" with "hana-free" Plan.

**Comment by renejeglinsky** [comment]
Hi @DanSchlachter ,
would be nice if you could look into the issues happening after deployment. Usually the guide should be self-contained and I'm not sure why it isn't (anymore). Maybe we have a gap wrt trial accounts here. 

Hi @johannes-vogel ,
could you check the error message that is misleading? Should probably be sth along "Neither "hdb" not "@sap/hana-client" could be found but is required"?

**Comment by renejeglinsky** [comment]
Hi @sfdfklskldf ,

Thank for opening this issue! As you've seen, we start working in it bit by bit.

The issue with spaces in your org name is sth we won't tackle here. It's an edge case and not best practice. Best is to use CLI-friendly org and space names.

All the best
René

**Comment by johannes-vogel** [comment]
> Hi @johannes-vogel , could you check the error message that is misleading? Should probably be sth along "Neither "hdb" not "@sap/hana-client" could be found but is required"?

I admit it's technical slang in the node world as the keyword is named _require_. We can adapt to found instead.

**Comment by DanSchlachter** [comment]
Hi,

there is no `cds add hana --for production` mentioned in the guide. The cds env looks different than in the guide, too.
So most likely it's just a missing hana configuration?

I'll try to add hana correctly and redeploy.

Thanks
Daniel

**Comment by sfdfklskldf** [comment]
> Thank for opening this issue! As you've seen, we start working in it bit by bit.
> 
> The issue with spaces in your org name is sth we won't tackle here. It's an edge case and not best practice. Best is to use CLI-friendly org and space names.
> 
> All the best René

Unforutnately I am not the person managing that part of our cloud account. Already our global account has a space in the name. And for me (as I am not able to create subaccounts) it looks like the space is propagated to each subaccount :-/

If space is not allowed maybe it SAP should directly restrict the creation of such names.
But it is obviously not restricted and therefore it has to work in an example.

**Comment by renejeglinsky** [comment]
The fix is [published](https://cap.cloud.sap/docs/guides/multitenancy/#_5-deploy-to-cloud).
Thanks again!
