### ISSUE TITLE
Test documentation has no info about authorisation and authentication.

### ISSUE THREAD

**Issue by spilger** [cap-js/docs#371]
As Developer that tries to develop tests I'd expect, that the documentation directly explains how to authorise and authenticate.

**Comment by renejeglinsky** [comment]
Hi @spilger 

Thanks for opening this issue. We'll look into it and also set you as reviewer on the PR when some content is created.

All the best,
René

**Comment by renejeglinsky** [comment]
And just to be sure: This is the documentation you're referring to, right?
https://cap.cloud.sap/docs/node.js/cds-test

**Comment by renejeglinsky** [comment]
I can't add you as reviewer, but feel free to review the linked PR.
