### ISSUE TITLE
Unable to hook on shutdown lifecycle event in node with Typescript

### ISSUE THREAD

**Issue by navjot50** [cap-js/docs#381]
I am using 6.8.4 release of cap and I was trying to write cleanup function for server shutdown. When I try to hook on the `shutdown` lifecycle event of cds, then I get compilation error that `Argument of type 'shutdown' is not assignable to parameter of type 'listening'`. Overall I can hook to `bootstrap`, `connect`, `listening`, `loaded`, `served`, `serving` lifecycle events but not the `shutdown event`.

```
cds.on("shutdown", () => {});
```

**Comment by daogrady** [comment]
On a related note: @navjot50, these missing types are already available in CDS 7. If you can upgrade, then that should fix the issue too.

Best,
Daniel

**Comment by navjot50** [comment]
@daogrady thanks for the quick response. Are there any breaking changes upgrading from CDS6 to CDS7?

**Comment by daogrady** [comment]
Hi @navjot50,

yes, as this is a major upgrade, you have to generally put special care into upgrading. You can find detailed information on the changed in our [June '23 changelog](https://cap.cloud.sap/docs/releases/jun23).

Best,
Daniel

**Comment by navjot50** [comment]
@daogrady thanks a lot.....I quickly tested by upgrading the CDS to version 7 and indeed the shutdown event is available with CDS7. This issue can be close.
