### ISSUE TITLE
Resources and Support should also link to the Continuous Influence Session for CAP

### ISSUE THREAD

**Issue by gregorwolf** [cap-js/docs#384]
Hello CAP Team,

on the page https://cap.cloud.sap/docs/resources/ there is no pointer to the [Continuous Influence Session for SAP Cloud Application Programming Model (CAP)](https://influence.sap.com/sap/ino/#/campaign/2280). I would suggest to add this link to give it more visibility.

Best Regards
Gregor

**Comment by renejeglinsky** [comment]
Thanks Gregor :)
It took a while but I'm preparing a PR for that 👍

**Comment by renejeglinsky** [comment]
It will be published with the upcoming release. Thanks again! :)

**Comment by renejeglinsky** [comment]
Hi Gregor,

We've added the customer influence session to our resources page in capire, to the release notes and also on our [community page](https://community.sap.com/topics/cloud-application-programming).
Thanks again for your suggestion.
