### ISSUE TITLE
Hiccup between node and java docs

### ISSUE THREAD

**Issue by johanneseschrig** [cap-js/docs#387]
It seems to me like some Java documentation is being shown under the node toggle:

https://github.com/cap-js/docs/blob/0c128b34586da767029807bcb6c47dfacbbdca40/guides/using-services.md?plain=1#L1513

![image](https://github.com/cap-js/docs/assets/6208191/c780c5f3-df58-4823-82b4-b17f3cfae9f2)

The indication to pascal case is contradictory to the above shown example.

**Comment by renejeglinsky** [comment]
Hi @johanneseschrig ,

Thanks for letting us know! I'll prepare a fix for that.

All the best,
René
