### ISSUE TITLE
not clear from docs that how to define a constant or literal string

### ISSUE THREAD

**Issue by Abhay-Joshi-Git** [cap-js/docs#399]
I want to define a constant or string literal type. But I could not find how to do it with the docs. If it's possible to do it, it should be easier to find out from docs.
example: in below given aspect, I want to define a constant for 'Tax'

```cds

aspect AccountInfo {
   taxIds                  : Association to many ExpenseBracket
                                 on  taxIds.owner          = $self
                                 and taxIds.identifierType = 'Tax'; //this should be defined as a constant
   taxReferenceNumber      : Integer;
}

```

**Comment by Abhay-Joshi-Git** [comment]
Thanks for reply.
I would like to define it separately. For example, similar to how we define a constant in Java or JavaScript. Then use that constant in place of 'Tax'.

I tried defining it something like

const TaxIdentifier = 'Tax';
or
type TaxIdentifier: String = 'Tax';

but those are not valid. I am looking for a valid way to define constant.

Thanks

**Comment by renejeglinsky** [comment]
With the string literal you define a default value, that's not what you want? Do you want to define that constant not in the context of an entity or aspect? Could you provide a sample how you think this should be written?

**Comment by Abhay-Joshi-Git** [comment]
yes, I would like to define it as a constant, which can be defined independent of entity or aspect and which can be used at multiple places. 
Sample -

```
const TaxIdentifier: String = 'Tax';

aspect AccountInfo {
   taxIds                  : Association to many ExpenseBracket
                                 on  taxIds.owner          = $self
                                 and taxIds.identifierType = TaxIdentifier; //used it here
   taxReferenceNumber      : Integer;
}

```

**Comment by Abhay-Joshi-Git** [comment]
Hi @renejeglinsky , a couple of days back I have added sample code above which I would like to write if constant can be defined.

**Comment by renejeglinsky** [comment]
Hi @Abhay-Joshi-Git ,

after asking some colleagues I have to say that this is not possible.

All the best,
René
