### ISSUE TITLE
 Inner Loop Development - is just introduced with no reference

### ISSUE THREAD

**Issue by njames** [cap-js/docs#402]
A lot of the CAP doco refers to things that people coming from a traditional ABAP context will have no clue about. 

I would recommend a link to an authoritative source to explain this further, instead of just leaving people to google what you are on about. ;)

**Comment by chgeo** [comment]
Can you give some examples of things that should be explained further?

**Comment by njames** [comment]
Mostly the 'Inner Loop' term just suddenly appeared on https://cap.cloud.sap/docs/get-started/jumpstart#mocked-platform-services but it may be new to some people 

This reference I found helped - https://www.getambassador.io/docs/telepresence/latest/concepts/devloop

**Comment by chgeo** [comment]
Thanks!  Will add this link in #418.
