### ISSUE TITLE
Compiler v2

### ISSUE THREAD

**Issue by njames** [cap-js/docs#403]
This [page about compiler v2](https://cap.cloud.sap/docs/cds/compiler-v2) has no context about when it applies or when v2 became available or how to check you have it. 

Please clarify

**Comment by renejeglinsky** [comment]
Hi Nigel,

Thanks for your feedback. We enhanced the page accordingly: https://github.com/cap-js/docs/commit/503d603d17988622e2baf82ef728dbeda7b433f4

All the best,
René
