### ISSUE TITLE
Deep Read Template literal

### ISSUE THREAD

**Issue by nocin** [cap-js/docs#419]
Hi,

Referring to this code line: https://github.com/cap-js/docs/blob/fdb79dc87e37f332a1cf2d3d0a73fd30104001ed/guides/providing-services.md?plain=1#L281C16-L281C16

In the docs the Deep Read query is written with the dot outside the literal: o.\`\*\`
```js
SELECT.from ('Orders', o => o.`*`, o.header (h => h.`*`, h.items('*')))
```

But this leads to the following syntax error in BAS:
![grafik](https://github.com/cap-js/docs/assets/35531968/9ba8ed7e-6f17-4a9d-9132-3e10037482ce)

Can it be that the correct syntax is either this
```js
SELECT.from ('Orders', o => o`.*`, o.header (h => h`.*`, h.items('*')))
```
or this?
```js
SELECT.from ('Orders', o => o(`*`), o.header (h => h(`*`), h.items('*')))
```

BR,
Nico

**Comment by sjvans** [comment]
thanks for reporting, @nocin
