### ISSUE TITLE
Upgrading multi tenant application after schema changes

### ISSUE THREAD

**Issue by sfdfklskldf** [cap-js/docs#427]
What is the correct process of upgrading a multi tenant application?
Assume a SAP CAP app that was deployed, subscribed and later schema changes.

How can a subscribed app upgrade the database?

**Comment by sfdfklskldf** [comment]
What I found is this: https://cap.cloud.sap/docs/java/multitenancy#database-update but this is for Java and I have a NodeJS backend. Also it is marked as "classic".

And I found this: https://cap.cloud.sap/docs/guides/multitenancy/mtxs#upgrade-tenants-%E2%86%92-jobs

But does this mean I have to use some tool like postman to trigger an upgrade?
Is there no automation available? Or a button somewhere on cloud frontend?

**Comment by renejeglinsky** [comment]
Hi @sfdfklskldf ,
I'm sorry I didn't respond here. I was sure I did as was definitely looking into this topic. I'll get back to you soon.
All the best,
René

**Comment by renejeglinsky** [comment]
Hi @sfdfklskldf ,
just recently, this was added to the multitenancy guide: https://cap.cloud.sap/docs/guides/multitenancy/?impl-variant=node#update-database-schema-for-tenants

Again, sorry that I didn't get back to you during the process.

All the best,
René

**Comment by sfdfklskldf** [comment]
Thanks
