### ISSUE TITLE
CDS Extension: @On-Event & Service Instance ID(s)

### ISSUE THREAD

**Issue by d062792** [cap-js/docs#432]
Hey colleagues,

I know that I can get the application name and ID with the following code snippet:
```
@On(event = ExtractPackageContext.CDS_NAME)
public void extractPackage(ExtractPackageContext context) {
    context.getCdsRuntime().getEnvironment().getApplicationInfo().getName();
    context.getCdsRuntime().getEnvironment().getApplicationInfo().getId();
}
```
However, I need to know the **instance ID** of the application where the event is running. 
Is it possible to get this information? And in addition to that, is it possible to get a list of all currently running instance IDs?

Best Regards,
Sascha

**Comment by renejeglinsky** [comment]
Hi @d062792 ,
It seems to me, that this is more a question for the community. You won't find developer support here.
If there's sth missing in the docs I'll surely and happily address that. It just takes usually longer than a question is open in the community. On the other hand I'd be glad, if you find the missing piece of information, when you contribute to capire and share your knowledge.

**Comment by d062792** [comment]
Thanks for the answer, I will try the other sources.
