### ISSUE TITLE
How to delete entries pointing to a entry that is going to be deleted?

### ISSUE THREAD

**Issue by sfdfklskldf** [cap-js/docs#433]
I try to delete all entries in a table that point to an element that will be deleted in an ongoing request.

What I try to do. In the service implementation I register:
```
this.on('DELETE', "SomeEntity", deleteReferencedEntities);
```
So each time DELETE of SomeEntity is requested it will call the handler.

The handler should delete all entries in a different table that pointing to this entry.
```
async function deleteReferencedEntities(req, next) {
    console.log("deleting all referenced entities with id = " + req.data.ID);
    let iNumberOfDeletedEntitities = await DELETE.from(OtherEntity).where ({referenced_ID:req.data.ID});
    console.log("deleted " + iNumberOfDeletedEntitities + " referenced entitites");
    next(); // use default handler
}
```
Locally with ``cds watch`` that works as expected.

Deployed to the cloud as multi tenant app I get following error:

```
   ERR [cds|...] - ❗️Uncaught Error: Transaction is already closed
   ERR at /home/vcap/app/node_modules/@sap/cds/libx/_runtime/hana/execute.js:154:36
   ERR at Statement.handle (/home/vcap/app/node_modules/hdb/lib/protocol/Statement.js:91:3)
   ERR at handleReply (/home/vcap/app/node_modules/hdb/lib/Client.js:278:15)
   ERR at receive (/home/vcap/app/node_modules/hdb/lib/util/Queue.js:114:18)
   ERR at Connection.receive (/home/vcap/app/node_modules/hdb/lib/protocol/Connection.js:390:3)
   ERR at TLSSocket.ondata (/home/vcap/app/node_modules/hdb/lib/protocol/Connection.js:243:12)
   ERR at TLSSocket.emit (node:events:512:28)
   ERR at addChunk (node:internal/streams/readable:343:12) 
   ERR at readableAddChunk (node:internal/streams/readable:316:9)
   ERR at Readable.push (node:internal/streams/readable:253:10)
```

So I assume my understanding of the documentation is wrong?
Is there a different way of deleting entries pointing to a deleted entry?

**Comment by renejeglinsky** [comment]
Hi @sfdfklskldf ,

I do see the connection to the documentation. But I guess, that you'd have a faster "time-to-answer" if you ask that question in the [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce). Of course I'd be interested in how we can improve our docs. I just want to clarify, that in this repo you don't get dev support. It's just not in my repertoire. What I do: I'm reaching out then to my colleagues. But that takes longer than questions usually stay open in the community.

**Comment by renejeglinsky** [comment]
Hi @sfdfklskldf ,

Have you posted this on the community?

**Comment by renejeglinsky** [comment]
Closing as we haven't had activity for a while. I hope you've achieved what you wanted to achieve.
