### ISSUE TITLE
Broken link in Node.js - Best Practices - Error Handling

### ISSUE THREAD

**Issue by sebastianesch** [cap-js/docs#434]
Hi!

The link https://www.joyent.com/node-js/production/design/errors at https://github.com/cap-js/docs/blob/50f71d76121cd9f846c583581c8d9a57ee707a36/node.js/best-practices.md?plain=1#L364 results in a 404 Page not found.

Kind regards,
Sebastian

**Comment by renejeglinsky** [comment]
Thanks Sebastian. I'll prepare a PR and link it here.

**Comment by renejeglinsky** [comment]
This is quite a huge document. Distilling it still make a big contribution to capire. Will look into it, but for the time being, I'll link to the archived version.
