### ISSUE TITLE
How to show a singel entry for logged in user?

### ISSUE THREAD

**Issue by sfdfklskldf** [cap-js/docs#435]
In the document https://cap.cloud.sap/docs/cds/cdl I see **$user only implemented for SAP HANA** that is already not so nice for local testing. Is there a way to provide a service that shows just the entry of the logged in user?

For example you have ``Persons`` as an entity set. 
My intention was something like:
```
@odata.singleton
MyData as projection on Persons where Persons.ID = $user.ID;
```

But looks like that won't work. Is there some similar solution described in the docs?

**Comment by sebastianesch** [comment]
Hi @sfdfklskldf,

it actually works - see https://github.com/sebastianesch/sap-cap-examples/blob/master/singleton-example/srv/example-service.cds and https://github.com/sebastianesch/sap-cap-examples/blob/master/singleton-example/test/example-service.http.

You just have to take into consideration, that $user.ID does not exist., there is only $user.id: https://cap.cloud.sap/docs/node.js/authentication#user-id

I think the remark that it's only implemented in HANA is left over from before the new database layer.

Kind regards,
Sebastian

**Comment by sfdfklskldf** [comment]
Ok, thanks a lot :)

**Comment by sfdfklskldf** [comment]
A follow up question. Is there a way to define the email address of mock user for local testing? Because in the cloud the ID is an email and local tests it just shows Anonymous as a user.

**Comment by renejeglinsky** [comment]
Hi,

Here's described how to define mock users explicitly: https://cap.cloud.sap/docs/node.js/authentication#mocked
Hope this helps.

**Comment by sebastianesch** [comment]
You can just use the email address as the username in package.json as explained in the docs Rene linked.

`"cds": {
  "requires": {
    "auth": {
      "kind": "mocked",
      "users": {
        "foo.bar@example.com": {
          "password": "<password>",
          "roles": [ "<role-name>", ... ],
          "attr": { ... }
        }
      }
    }
  }
}`

Then you use the email address to login and it available in the $user variable.

Kind regards,
Sebastian

**Comment by renejeglinsky** [comment]
I guess this can be closed then, right? If not please re-open if needed. Thanks.
And thanks @sebastianesch for providing your expertise here. Very much appreciated!
