### ISSUE TITLE
cds compile documentation issue

### ISSUE THREAD

**Issue by AjitKP** [cap-js/docs#437]
https://cap.cloud.sap/docs/guides/databases#using-cds-compile-2-dialect

<img width="1728" alt="image" src="https://github.com/cap-js/docs/assets/25340339/712df69b-7b62-43d7-97d3-ad299afd0590">

In this documentation, it is mentioned that postgres dialect will work (TIP section) . however it is not working.

Error: Unknown model processor: cds.compile.to.postgres

**Comment by renejeglinsky** [comment]
Hi @AjitKP ,

Thanks for opening this issue. I'm aware of this and already working on a fix. Please use `cds deploy --to <dialect> --dry` to get the required DDL.
