### ISSUE TITLE
Postgresql create deploy script example generates an invalid 'package.json' file 

### ISSUE THREAD

**Issue by sedacrivity** [cap-js/docs#459]
The Postgresql create deploy script generates an invalid 'package.json' file 

```sh
echo '{"dependencies": { "@sap/cds": "*", "@cap-js/postgres": "*"},  "scripts": {    "start": "cds-deploy",}}' > gen/pg/package.json
```
contains an invalid ',' after "cds-deploy"

```
npm ERR! JSON.parse Unexpected token "}" (0x7D) in JSON at position 101 while parsing near "...tart\": \"cds-deploy\",}}\n"
npm ERR! JSON.parse Failed to parse JSON data.
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.
```

https://cap.cloud.sap/docs/guides/databases-postgres#create-the-shell-script

**Comment by renejeglinsky** [comment]
Hi,

thanks for opening this issue. It has already been fixed, just not yet shipped: https://github.com/cap-js/docs/pull/448

All the best,
René
