### ISSUE TITLE
SQLite - Skipped Virtuals - Example and explanation don't match

### ISSUE THREAD

**Issue by sebastianesch** [cap-js/docs#466]
The results in
https://github.com/cap-js/docs/blob/c4ffb72ba1b8737c3de07109d0b745ee2296c01a/guides/databases-sqlite.md?plain=1#L713-L717 don't match the explanations, if I'm not mistaken.

With the example

```
entity Foo {
  virtual foo : Integer;
  bar : Integer;
}
```

The outcome should be

```
SELECT.from('Foo')         //> [{ bar:1 }, ...]
SELECT('foo').from('Foo')  //> ERROR: no columns to read
```

instead, as `foo` is defined as `virtual`and `bar` is not, right?

Kind regards,
Sebastian

**Comment by renejeglinsky** [comment]
Hi @sebastianesch ,

Thanks for catching this! It's addressed in #469 👍
