### ISSUE TITLE
Does @assert.range support dynamic comparison with other attribute value?

### ISSUE THREAD

**Issue by sfdfklskldf** [cap-js/docs#490]
Is there a way to define an @assert.range based on properties.
For example if you have a time range to ensure the from is before the end date.
Or is there a different way to handle that?
Or is the only solution registering a CREATE and UPDATE handler for the such field validation?

Links to unanswered SAP blog questions (from 2021):

https://answers.sap.com/questions/13422473/cap-date-dependency.html
https://answers.sap.com/questions/13442673/-48.html

**Comment by danjoa** [comment]
Currently there's no such option, so indeed has to be done programmatically. 
But we plan to add this 

@stewsk

**Comment by sfdfklskldf** [comment]
Would be quite helpful otherwise such checks must be implemented for create and update calls all the time. Would be good to have as may restrictions as possible defined on the schema to avoid duplicate validations.

**Comment by renejeglinsky** [comment]
Hi @sfdfklskldf ,
Thanks for your valid request. As this is on our backlog and we are not tracking feature requests here, I'm closing this issue. Nevertheless, you should get a message here after the implementation.

**Comment by stewsk** [comment]
Corresponding CAp backlog item: https://github.tools.sap/cap/dev/issues/421
