### ISSUE TITLE
Post to remote service returns "TypeError: Cannot read properties of undefined (reading 'length')"

### ISSUE THREAD

**Issue by MiqueiasMaia** [cap-js/docs#496]
I have this function in a NodeJS application using @sap/cds version 7.3.0:

```js
static async getEquipmentSet() {
        try {
            const api = await cds.connect.to('sap-odata-service');
            const result = await api.get(`EquipmentSet`);
            return result;
        } catch (error) {
            console.log(error);
        }
}
```

This previous GET function returned data from the remote service `'sap-odata-service'` configured in `cdsrc.json` file.

But the following POST method returns an error:
```js
    static async postHourmeter(equipmentData, measurementPointId) {
        try {
            const payload = this.getHourmeterPayload(equipmentData, measurementPointId);
            const api = await cds.connect.to('sap-odata-service');
            const result = await api.post(`MeasureDocumentSet`, payload);
            return result;
        } catch (error) {
            console.log(`The error is:`);
            console.log(error);
        }
    }
```

Errors:
<img width="1112" alt="Screenshot 2023-10-23 at 11 49 46" src="https://github.com/cap-js/docs/assets/18472559/40aac4be-9226-48f3-84f4-0d66f1f436cc">

Does anyone know how to fix it?

**Comment by renejeglinsky** [comment]
HI @MiqueiasMaia ,
This questions seems more appropriate to be asked in the [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce). Or if it's a bug, pls file an incident. More information on how to get support is doucmented here: https://cap.cloud.sap/docs/resources/

In this repository, we only want to solve documentation-related questions and contributions. We do not intend to answer general questions or bug reports. Thanks for your understanding.

All the best René
