### ISSUE TITLE
incorrect uaa references -> auth

### ISSUE THREAD

**Issue by njames** [cap-js/docs#514]
Here https://cap.cloud.sap/docs/node.js/cds-env#env-cds-config

and 

 https://cap.cloud.sap/docs/node.js/authentication#prepare-local-environment

there are references to `uaa` when they should be `auth`

In the second link there is: 
`cds env list requires.uaa --resolve-bindings --profile hybrid`

but that returns nothing.

Rather:

`cds env list requires.auth --resolve-bindings --profile hybrid` 

returns what I expect as `auth` is what is configured in the `.cdsrc-private.json`
```
  "requires": {
    "[hybrid]": {
      "auth": {
```

**Comment by renejeglinsky** [comment]
Thanks Nigel for bringing this up.

@johannes-vogel Can you confirm this? Then I'll go ahead and make the needed changes.
