### ISSUE TITLE
Foreign key constraint not created as INITIALLY DEFERRED

### ISSUE THREAD

**Issue by d-schroeder** [cap-js/docs#515]
Hello,

I'm currently trying to make use of the recently added foreign key constraint option in CAP 7. Unfortunately all of my constraints (tried with multiple hdi containers) are being set as "initially immediate", instead of "initially deferred". According to the [documentation](https://cap.cloud.sap/docs/guides/databases#db-constraints) there shouldn't really be a way to achieve this, even if I wanted to.

Using DBeaver I can see the unwanted deferability setting on the HANA cloud db:
<img width="675" alt="image" src="https://github.com/cap-js/docs/assets/79696241/af1878b0-61d6-4e73-8434-e74198c8149e">

Oddly, the DDL seems to be correct:
<img width="1050" alt="image" src="https://github.com/cap-js/docs/assets/79696241/d3cbb502-184a-4ffc-b569-e38829fed8dc">

and seems to match the created .hdbconstraint file:
```sql
  CONSTRAINT c__[constraint]
  ON [table]
  FOREIGN KEY([field])
  REFERENCES [referencedTable](ID)
  ON UPDATE RESTRICT
  ON DELETE CASCADE
  VALIDATED
  ENFORCED
  INITIALLY DEFERRED
```

I'm using these versions:
<img width="381" alt="image" src="https://github.com/cap-js/docs/assets/79696241/d1b8517b-ba5e-4778-9e51-7275e0febc92">

This feature is also supported by SAP HANA Cloud, as we can see in the [documentation](https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/alter-table-statement-data-definition?locale=en-US&q=initially%20deferred).
The same problem exists when using my HANA Express, too.

Any idea what this may be caused by?

Because of this I can't insert entries within the same transaction in the "wrong" order.

**ALSO: CAP does NOT show me an error after failing to insert data with missing references! It also does not roll back the DB transaction, it just doesn't insert some data and then commits the data that is "correct"!**

**Comment by renejeglinsky** [comment]
Hi @d-schroeder ,
Sad to hear that it's not working for you. I haven't heard of this problem before and ask you to please ask this as a question on the [SAP Community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce). In this repository here, we aim to address everything related to documentation. Our development colleagues are active on the community and also the whole community is very helpful and active.
Thanks,
René

**Comment by patricebender** [comment]
@d-schroeder it seems like the constraints can not be deffered, because the `ON DELETE` rule is set to `CASCADE`. From the [HANA Docs](https://help.sap.com/docs/SAP_HANA_PLATFORM/4fe29514fd584807ac9f2a04f6754767/20d58a5f75191014b2fe92141b7df228.html):

> DEFERRED - referential constraints are checked at commit time. If a referential constraint is violated, then the transaction is rolled back. Also, if <referential_triggered_action> is set to something other than RESTRICT, then the referential constraint check on the parent (referencing) table is not deferred and instead is checked immediately.a

**Comment by d-schroeder** [comment]
@patricebender The same problem also exists on foreign keys where the actions are set to restrict!
In a local sqlite DB it all seems to work fine, please really test this stuff against a HANA Cloud DB.

<img width="351" alt="image" src="https://github.com/cap-js/docs/assets/79696241/fe00cdf5-475f-41c8-b6c7-52011015d7fc">

**Comment by patricebender** [comment]
@d-schroeder, The documentation, does not seem to reflect what I have observed. I have prepared the following test script, which works perfectly fine on my HANA Cloud:

```sql
-- generated by cds-compiler version 4.3.3
CREATE TABLE Books (
  ID INTEGER NOT NULL,
  title NVARCHAR(5000),
  author_ID INTEGER NOT NULL,
  PRIMARY KEY(ID, author_ID)
) WITH ASSOCIATIONS (
  MANY TO ONE JOIN Authors AS author ON (author.ID = author_ID)
);

-- generated by cds-compiler version 4.3.3
CREATE TABLE Authors (
  ID INTEGER NOT NULL,
  PRIMARY KEY(ID)
) WITH ASSOCIATIONS (
  MANY TO MANY JOIN Books AS books ON (books.author_ID = ID)
);

-- generated by cds-compiler version 4.3.3
ALTER TABLE Books
ADD CONSTRAINT c__Books_author
FOREIGN KEY(author_ID)
REFERENCES Authors(ID)
ON UPDATE RESTRICT
ON DELETE CASCADE
VALIDATED
ENFORCED
INITIALLY DEFERRED;

-- INSERT testdata
INSERT INTO Authors (ID) VALUES (1);
INSERT INTO Authors (ID) VALUES (2);
INSERT INTO Authors (ID) VALUES (3);

INSERT INTO Books (ID, title, author_ID) VALUES (2, 'Book 2', 1);
INSERT INTO Books (ID, title, author_ID) VALUES (3, 'Book 3', 2);
INSERT INTO Books (ID, title, author_ID) VALUES (1, 'Book 1', 1);
INSERT INTO Books (ID, title, author_ID) VALUES (4, 'Book 4', 3);

COMMIT;

-- INSERT Books with non-existing author

INSERT INTO Books (ID, title, author_ID) VALUES (1, 'Book 1', 42); -- everything OK

COMMIT; -- CONSTRAINT violation happen here

UPDATE BOOKS SET author_ID = 42 WHERE ID = 3 -- everything OK

COMMIT; -- CONSTRAINT violation happen here
```

If you can, open a Service Now Ticket for the HANA Colleagues. If that is not possible for you, please go with Rene's suggestion and open a ticket on [answers.sap.com](https://community.sap.com/search/?ct=all&mt=73554900100700000996&mt=73554900100800000266&q=HANA). It would be nice if you could provide a sample repository with detailed steps to reproduce your issue.

**Comment by d-schroeder** [comment]
@patricebender  Please check if the following case works for you;

```sql
BEGIN;
INSERT INTO Books (ID, title, author_ID) VALUES (1, 'Book 1', 4); 
INSERT INTO Authors (ID) VALUES (4);
COMMIT;
```

This is the problematic case I described in the issue, which should be possible with the deferred foreign key. For me, the equivalent of the Books entity is not getting inserted, without an error being thrown and the transaction not being rolled back!

**Comment by d-schroeder** [comment]
Interesting, for my data model it creates the check time as immediate, although it shouldn't....

**Comment by patricebender** [comment]
> Interesting, for my data model it creates the check time as immediate, although it shouldn't....

Could you please execute the above query and double check the `CHECK_TIME`?

→ I noticed that in DBeaver, the same constraint appears as `INITIALLY_IMMEDIATE` in the graphical view:
<img width="512" alt="Screenshot 2023-11-03 at 14 17 37" src="https://github.com/cap-js/docs/assets/23496018/58364ac0-13b3-4bde-8416-402522c45c31">

**Comment by d-schroeder** [comment]
Wow, so DBeaver does display this wrongly indeed!

<img width="508" alt="image" src="https://github.com/cap-js/docs/assets/79696241/ab42375d-d502-43dd-9bfa-49deddcd586d">

This makes my failing insert even worse to debug I guess?!

**Comment by patricebender** [comment]
> ```sql
> BEGIN;
> INSERT INTO Books (ID, title, author_ID) VALUES (1, 'Book 1', 4); 
> INSERT INTO Authors (ID) VALUES (4);
> COMMIT;
> 
> SELECT * FROM BOOKS b ;
> ```
> 
> ID	TITLE	AUTHOR_ID
> 2	Book 2	1
> 1	Book 1	4
> → works on my end
> 
> I have opened a ticket on [answers.sap.com](https://answers.sap.com/questions/14002473/why-does-deferred-foreign-key-constraint-work-whil.html)
> 
> additional info:
> 
> ```sql
> SELECT CONSTRAINT_NAME, UPDATE_RULE, DELETE_RULE, CHECK_TIME FROM REFERENTIAL_CONSTRAINTS WHERE table_name = 'BOOKS';
> ```
> 
> CONSTRAINT_NAME	UPDATE_RULE	DELETE_RULE	CHECK_TIME
> C__BOOKS_AUTHOR	RESTRICT	CASCADE	INITIALLY_DEFERRED

If you execute the same statements as I did above, what is the result of `SELECT * FROM BOOKS`? Maybe your insert "just works"?

**Comment by d-schroeder** [comment]
I don't have a running version of the bookshop right now, I'll try it later. However in my project, an example that's essentially the same (data relation wise) is not working.
