### ISSUE TITLE
Fail to patch entity collection in java

### ISSUE THREAD

**Issue by Lynnes001** [cap-js/docs#530]
Hi CAP Team,

I am following [this section](https://cap.cloud.sap/docs/advanced/odata#odata-patch-collection) to implement a batch request for my service. 

The CDS definition is described below
```cds
// schema.cds
entity ExchangeRateDto {
    key id : UUID;
    key displayId : String(32);
        exechangeRate : Decimal(10,2);
};


//MyService.cds
@Capabilities.UpdateRestrictions.DeltaUpdateSupported
service MyService {
    entity ExchangeRate as projection on ExchangeRateDto {*};
}
```

Regular post/get apis work as expected.

I tested CAP PATCH batch to URL: `localhost:8080/odata/v4/MyService/ExchangeRate` via following payload

```json
{
	"@context": "#$delta",
	"value": [
		{
			"id": "34642296-8b91-4145-a579-0e4d5a51cdb6",
			"displayId": "ID-1",
			"exechangeRate": 7.83
		},
		{
			"id": "44642296-8b91-4145-a579-0e4d5a51cdb6",
			"displayId": "ID-2",
			"exechangeRate": 7.83
		}
	]
}
```

But got the response with 405 method not allowed with body 
```
{
	"error": {
		"code": "405005",
		"message": "Entity '{}' is not delta updatable"
	}
}
```

Besides, I tested odata-style $batch to URL `localhost:8080/odata/v4/MyService/$batch`

```json
{
	"requests": [
		{
			"id": "1",
			"method": "post",
			"url": "/MyService/ExchangeRate"
			"body": {
				"id": "34642296-8b91-4145-a579-0e4d5a51cdb6",
				"displayId": "ID-1",
				"exechangeRate": 7.83
			}
		},
		{
			"id": "2",
			"method": "post",
			"url": "/MyService/ExchangeRate",
			"body": {
				"id": "44642296-8b91-4145-a579-0e4d5a51cdb6",
				"displayId": "ID-2",
				"exechangeRate": 7.83
			}
		}
	]
}
```

but get error response  400 bad request
```json
{
	"error": {
		"code": "400",
		"message": "Content-Type at line '0' should be 'multipart/mixed' but is 'application/json'."
	}
}
```

Not sure which part goes wrong? Would you kindly advise?

**Comment by renejeglinsky** [comment]
Hi @Lynnes001,

We are not offering support in this repository. Only issues related to documentation are supported here.
I searched in the community for sth helpful and maybe this helps: https://answers.sap.com/questions/12995266/cap-batch-request-for-odata-apis.html

If not, feel free to post your question there. The community is very active and also CAP experts are monitoring questions there.

All the best,
René
