### ISSUE TITLE
Joint Columns Missing When Inserting to Views

### ISSUE THREAD

**Issue by Lynnes001** [cap-js/docs#531]
Hi CAP Team,

I am following the [Resolvable View and Projection](https://cap.cloud.sap/docs/java/query-execution#updatable-views) section to implement a view for CRUD. My definition is shown below

```cds
// schema.cds
entity HeaderAsso {
    key id : UUID;
        displayId : String(32);
        exc_from : String(8);
        exc_to : String(8);
        tcurr: Association to one TCURR on tcurr.FCURR = exc_from and tcurr.TCURR = exc_to;
}
entity TCURR {
    key MANDT : String(3);
    key KURST : String(4);
    key FCURR : String(5);
    key TCURR : String(5);
    key GDATU : String(8);
        UKURS : Decimal(9, 5);
        FFACT : Decimal(9, 0);
        TFACT : Decimal(9, 0);
}

// MyService.cds
entity HeaderJoinAsso as projection on HeaderAsso{
        *,
        tcurr.UKURS as UKURS,
    };
```

My design is that I could insert into `HeaderJoinAsso`, and the payload will go to both `HeaderAsso` and `TCURR`. 

I post the following payload and it succeed, but only `HeaderAsso` is inserted.
```json
{
	"id": "34642296-8b91-4145-a579-0e4d5a51cdb6",
	"displayId": "ID-1",
	"exc_from": "EUR",
	"exc_to": "USD",
	"type": "M",
	"effective_date": "2021-08-09",
	"UKURS": 1.15
}
```

Does it mean that, while inserting to a view, I can only get the validation for the associated entity columns but no deep insertion? I will need to create a handler class to do insertion for associated entities?

Thanks a lot!

**Comment by renejeglinsky** [comment]
Hi @Lynnes001 ,

probably this helps: https://cap.cloud.sap/docs/java/query-execution#cascading-over-associations

Note, that cascading over annotations is not considered best practice.

**Comment by Lynnes001** [comment]
Okay then, I went on doing with handlers.
