### ISSUE TITLE
Community Plugins

### ISSUE THREAD

**Issue by gregorwolf** [cap-js/docs#549]
Great to see the list of [CAP Plugins & Enhancements](https://cap.cloud.sap/docs/plugins/). Can this list be also extended with Community Plugins? First additions could be:

- [cds mysql](https://github.com/Soontao/cds-mysql)
- [cds-launchpad-plugin](https://github.com/geert-janklaps/cds-launchpad-plugin)
- [SAP BTP Feature Toggle Library](https://github.com/cap-js-community/feature-toggle-library)

**Comment by renejeglinsky** [comment]
Thank you Gregor!
I'll get back to you soon.

**Comment by renejeglinsky** [comment]
Hi Gregor,
we decided to not mention community plugins that are not SAP-maintained on the plugins page. What we are going to do is, to add a note and mention/link the CAP community so that people find all plugins.
