### ISSUE TITLE
Does CAP support OData API like [GET] /odata/v4/service/entity/{key} ?

### ISSUE THREAD

**Issue by Lynnes001** [cap-js/docs#557]
Hi Team,

i learnt that the document [here](https://cap.cloud.sap/docs/guides/providing-services#serving-crud) mentioned CAP support such API like /service/entity/{key}. It does not work from my end, and please also see the [answer from the community](https://answers.sap.com/questions/14012100/does-cap-expose-classical-odata-api-that-put-key-i.html) which said it does not support. There seems like a conflict with the document. Would you please help to check? Is it only supported in Node-based CAP?

Thanks!

**Comment by renejeglinsky** [comment]
Hi @Lynnes001 ,

from which part of the document did you learnt that this is supported? Please provide more details so that we're able to improve.
Nevertheless, the statement from @beckermarc in the community is correct. @beckermarc Do you see a way to improve here?

**Comment by Lynnes001** [comment]
Hi @renejeglinsky i learnt from this section from Capire https://cap.cloud.sap/docs/guides/providing-services#serving-crud

> Serving CRUD Requests
The CAP runtimes for [Node.js](https://cap.cloud.sap/docs/node.js/) and [Java](https://cap.cloud.sap/docs/java/) provide generic handlers, which automatically serve all CRUD requests to entities for CDS-modelled services on top of a default [primary database](https://cap.cloud.sap/docs/guides/databases).
This comprises read and write operations like that:
GET /Books/201 → reading single data entities
GET /Books?... → reading data entity sets with advanced query options
POST /Books {....} → creating new data entities
PUT/PATCH /Books/201 {...} → updating data entities
DELETE /Books/201 → deleting data entities

@schiwekM Thanks a lot. 

Seems the conclusion is that it's only supported in Node.

**Comment by beckermarc** [comment]
Yes only supported in Node.js currently, but we have a backlog for that for CAP Java: https://github.wdf.sap.corp/cds-java/home/issues/1218
