### ISSUE TITLE
Issue with extending annotations of entity over defined ones via aspect

### ISSUE THREAD

**Issue by thecoldstone** [cap-js/docs#577]
Hi, 
I have the following issue related to extending already existing annotations on top of the entity.
Follow the example: https://github.tools.sap/I540823/tutorial-be/blob/aspect-issue/db/schema.cds#L53

It shows the following error 
![Screenshot 2023-12-08 at 16 55 56](https://github.com/cap-js/docs/assets/44757028/6f00e2e8-e8fb-4708-9286-07f26d741625)

However, once the annotation over Gender entity is removed, in that case only aspect annotation is applied, it shows  populated line items from aspect in metadata.
![Screenshot 2023-12-08 at 17 06 28](https://github.com/cap-js/docs/assets/44757028/a9438a09-697d-4859-b66c-b20aba112e7a)

**Comment by renejeglinsky** [comment]
Hi @thecoldstone ,

Please ask this question in the [community](https://answers.sap.com/questions/ask.html?primaryTagId=9f13aee1-834c-4105-8e43-ee442775e5ce&topics=Visual%20Studio%20Code&b=%3Cp%3E%3Cb%3EYour%20environment%20(run%20the%20following%20commands)%3A%3C%2Fb%3E%3C%2Fp%3E%3Cul%3E%3Cli%3Ecds%20-v%3C%2Fli%3E%3Cli%3Enode%20-v%3C%2Fli%3E%3Cli%3Ejava%20-version%20(if%20applicable)%3C%2Fli%3E%3C%2Ful%3E%3Cp%3E%3Cb%3ESteps%20to%20reproduce%3A%3C%2Fb%3E%3C%2Fp%3E%3Cul%3E%3Cli%3Ecommand%20line%20used%3C%2Fli%3E%3Cli%3Eactions%20in%20IDE%3C%2Fli%3E%3C%2Ful%3E%3Cp%3E%3Cb%3EAdditional%20information%20(if%20applicable)%3A%3C%2Fb%3E%3C%2Fp%3E%3Cul%3E%3Cli%3Eproject%20files%3C%2Fli%3E%3Cli%3Elogs%3C%2Fli%3E%3Cli%3Escreenshots%3C%2Fli%3E%3Cli%3E...%3C%2Fli%3E%3C%2Ful%3E) as we don't do development support in here. If you find the documentation is wrong or unclear please let me know and we'll fix it.

Thanks,
René
