### ISSUE TITLE
CSURF package deprecated

### ISSUE THREAD

**Issue by aboccassiniavvale** [cap-js/docs#588]
Hi all,

following the best practices page (https://cap.cloud.sap/docs/node.js/best-practices#securing-your-application), I came across the CSRF token topic.
Reading the documentation it is suggested to install the "csurf" package. Clicking on the provided link (https://www.npmjs.com/package/csurf) I discover that this is a deprecated package.

In fact, even proceeding with the installation I have some problems using my CAP application oData from a SAPUI5 app. Specifically all "POST" requests are being rejected. 

What other library will need to be used to maintain compatibility with the CAP application and SAPUI5 apps?

Thanks
Alessandro

**Comment by renejeglinsky** [comment]
Hi @aboccassiniavvale ,
thank you for getting in touch.

@johannes-vogel could you please comment here or propose a doc change accordingly if necessary?

Thanks René

**Comment by johannes-vogel** [comment]
I personally don't know an alternative.
For now, I think we shouldn't refer to the deprecated package from our docs.

**Comment by renejeglinsky** [comment]
I opened a PR to remove the deprecated package.
@aboccassiniavvale For your issues: Please search in the [community](https://community.sap.com/topics/cloud-application-programming) or post a question there. We can't offer development support here.
