### ISSUE TITLE
Swagger UI does not work

### ISSUE THREAD

**Issue by horsemanjackyliu** [cap-js/docs#593]
https://cap.cloud.sap/docs/advanced/openapi#embedded-in-node-js

I do exactly as the following

In your project, execute

npm install --save-dev cds-swagger-ui-express
Usage
Have this in your [server.js](https://cap.cloud.sap/docs/node.js/cds-server#custom-server-js):

const cds = require ('@sap/cds')
module.exports = cds.server
 
if (process.env.NODE_ENV !== 'production') {
  const cds_swagger = require ('cds-swagger-ui-express')
  cds.on ('bootstrap', app => app.use (cds_swagger()) )
}
Swagger UI is then served on /$api-docs/<service-path>, like http://localhost:4004/$api-docs/browse/
But the Swagger UI does not work as the following screen shot .
![image](https://github.com/cap-js/docs/assets/74337345/715e139c-a18b-45f7-801a-e478add694a8)
![image](https://github.com/cap-js/docs/assets/74337345/be820d2c-f7f8-45c3-9cab-f7233d500f5b)

**Comment by renejeglinsky** [comment]
Hi @horsemanjackyliu 

Thanks for opening this issue. Do you see this "Open API preview" suffix?

![image](https://github.com/cap-js/docs/assets/32062331/5e7eb5aa-3854-42eb-a2c7-2546bada7e46)

The [ReadMe](https://github.com/chgeo/cds-swagger-ui-express) of the package contains some more information. Does that help?

**Comment by horsemanjackyliu** [comment]
Thanks! Got it ! Create github for this in https://github.com/horsemanjackyliu/capswaggersample in branch master .
