### ISSUE TITLE
Add link to  Custom Streaming (beta) in the Serving Media Data documentation

### ISSUE THREAD

**Issue by gregorwolf** [cap-js/docs#602]
Hi @renejeglinsky ,

in the issue #497 I've mentioned the issue that a search for mediaContentType does not return any result. But the page [Custom Streaming (beta)](https://cap.cloud.sap/docs/node.js/best-practices#custom-streaming-beta) is also not mentioned on the page [Serving Media Data](https://cap.cloud.sap/docs/guides/media-data). I think this should be improved.

Best Regards
Gregor

**Comment by renejeglinsky** [comment]
Hi Gregor,
I've not forgotten about your issues. It's be included in the next CAP release.

All the best
René
