### ISSUE TITLE
Bug: Built-in Type - no input validation for default string length

### ISSUE THREAD

**Issue by SpyZzey** [cap-js/docs#614]
Environment:
- Deployed on SAP BTP Cloud Foundry
- Database: SAP HANA Cloud
- CDS 7.5.2
- NodeJs v18.17.1

CAP does not validate the user input in Requests for String attributes where no length is specified:
As of the documentation (https://cap.cloud.sap/docs/cds/types), the default length for an attribute of type String with SAP HANA is 5000.
```
entity Test : cuid, managed {
   name: String;
   // ...
}
```
should be equal to
```
entity Test : cuid, managed {
   name: String(5000);
   // ...
}
```

However, the first example returns a 

> 500: Internal Server Error,

when creating a Test-Entity that has a name with length > 5000. The second example returns a 

> 400: Deserialization Error: Invalid value '...'. for property "name". The length of the Edm.String value must not be greater than the MaxLength facet value (5000).

The default length of 5000 is only set in SAP HANA and not validated in the application. Thus, creating a console output of

> [cds] - Error: inserted value too large for column: Failed in "NAME" column with the value

**Comment by renejeglinsky** [comment]
Hi @SpyZzey ,

thank you for getting in touch. So you're not questioning that the docs are incorrect but you're arguing that the input validation is not as you'd expect it, right?
@stewsk Could you comment if this is a bug or if we need to be more explicit about this in our docs?

**Comment by stewsk** [comment]
Need to pass that on to runtime colleagues, as the input validation happens ther.
@johannes-vogel can you comment on this?

**Comment by johannes-vogel** [comment]
The CDS model does not contain a length limit, hence no limit is checked. 
It's btw. also not part of the edmx.

If you require a limit, please simply specify it in the model.

**Comment by SpyZzey** [comment]
Alright, I appreciate your prompt responses. However, I believe the documentation could be more precise. I assume that the statement 

>  Argument length is optional → use options cds.cdsc.defaultStringLength and cds.cdsc.defaultBinaryLength to control the project-specific default length used for OData and SQL backends. If not set, default length 5000 is used for SAP HANA and default length 255 is used for all other SQL backends.

means that I don't have to specify a limit in my model, and it will default to 5000. But considering your responses, 

> If not set, default length 5000 is used for SAP HANA and default length 255 is used for all other SQL backends.

seems to apply purely to the database schema, which IMO isn't 100% clear from the documentation.

**Comment by danjoa** [comment]
Thanks for reporting @SpyZzey , we agree with your conclusion. 
@renejeglinsky We need to add something like this to the docs (the second sentence is important):

Note that default length are only applied on database level. No length checks will be applied on service level on inbound data. Specify fixed lengths to get these.
