### ISSUE TITLE
marking input parameter for function in service as optional

### ISSUE THREAD

**Issue by Abhay-Joshi-Git** [cap-js/docs#638]
Documentation does not specify what is a way to mark input parameter as optional for function or action in CDS service.

E.g. in following service, function `getCurrentData `accepts a parameter `id `but that should be optional; user of function should be able to call function without passing the parameter

```js
service testService {
    function getCurrentData(
         id: string // this should be marked as optional 
    ) return String(256);
}
```

Please specify a way by which a parameter in function or action can be marked as optional or default.

Thanks

**Comment by renejeglinsky** [comment]
Hi @Abhay-Joshi-Git ,

thank you for opening this issue.

@stewsk , can you answer this question?

**Comment by renejeglinsky** [comment]
Hi @Abhay-Joshi-Git ,
marking an input parameter as optional is not yet possible. We'll announce this in our release notes as soon as this should be possible.

All the best René
