### ISSUE TITLE
Cookbook - Multitenancy - Subscribe Tenants: Unauthorized due to missing Authorization header in http example

### ISSUE THREAD

**Issue by gregorwolf** [cap-js/docs#655]
Hi,

in the Cookbook - Multitenancy - Subscribe Tenants [3. Subscribe Tenants](
https://cap.cloud.sap/docs/guides/multitenancy/?impl-variant=node#_3-subscribe-tenants) there is this http request sample:

```
POST http://localhost:4005/-/cds/deployment/subscribe HTTP/1.1
Content-Type: application/json

{ "tenant": "t1" }
```

But it results in this error:

```
{
  "error": {
    "code": "401",
    "message": "Unauthorized"
  }
}
```

This is caused by the missing Authorization header. This request is a working example:

```
POST http://localhost:4005/-/cds/deployment/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Basic alice:

{ 
  "tenant": "t1"
}
```

CU
Gregor

**Comment by renejeglinsky** [comment]
Thank you Gregor! This is fixed and will be shipped with the next release.
