### ISSUE TITLE
Please document cds.entities

### ISSUE THREAD

**Issue by dinurp** [cap-js/docs#656]
Documentation is missing for `cds.entities` in the [documentation for cds facade](https://cap.cloud.sap/docs/node.js/cds-facade#properties). It is a shortcut to `cds.db.entities`, is it not? But there are references in release notes ([example](https://cap.cloud.sap/docs/releases/archive/2022/aug22#changes-in-node-js)) where `cds.entities` is used as a function with namespace as an argument. So, is [documentation of cds.Service.entities](https://cap.cloud.sap/docs/node.js/core-services#entities) complete? It does not mention the extra argument.

**Comment by renejeglinsky** [comment]
Hi @dinurp,
thanks for you question. I'll get back to you next week.
