### ISSUE TITLE
Please correct in documentation caching behavior of cds.connect.to

### ISSUE THREAD

**Issue by dinurp** [cap-js/docs#657]
In the documentation of [cds.connect.to (name, options?)](https://cap.cloud.sap/docs/node.js/cds-connect#cds-connect-to-name-options-%E2%86%92-service), it i stated that _subsequent connects with the same service name return the initially connected one_. This does not appear to be correct when the method is called with 2 arguments. Any cached instance is not returned. Instead a new instance is created and replaced in the cache.  Could you pleased update the documentation.

**Comment by renejeglinsky** [comment]
Thanks @dinurp for opening this issue. We fixed that in the mentioned PR.
Cheers René
