### ISSUE TITLE
Please correct the documentation of cds.requires

### ISSUE THREAD

**Issue by dinurp** [cap-js/docs#658]
In the [documentation of cds.requires](https://cap.cloud.sap/docs/node.js/cds-facade#cds-requires), it is stated 
_is a convenience shortcut to `cds.env.requires`._ This does not seem to the case.  For example, I inspected these properties in a repl 
session and observed the following.
```
> Object.keys(cds.requires)
[ 'Trippin' ]
> Object.keys(cds.env.requires)
[ 'auth', 'TripPinService', 'db' ]
```
The returned objects from these 2 do not even seem to have the same properties.

I had the following entry in `.cdsrc`
```
{
    "requires": {
      "TripPinService": {
        "kind": "odata",
        "model": "srv/external/TripPinRESTierService",
        "service": "Trippin"
      }
    }
  }

```

**Comment by danjoa** [comment]
Good catch → updated the docs as follows:

### cds. requires {.property}

... is an overlay and convenience shortcut to [`[cds.env.requires](file:///Users/D044173/cap/docs/@external/node.js/cds-facade.md#cds-env)`](#cds-env), with additional entries for services with names different from the service definition's name in cds models. For example, given this service definition:

```cds
service ReviewsService {}
```

... and this configuration:

```jsonc
{ "cds": {
  "requires": {
    "db": "sqlite",
    "reviews" : {
      "service": ReviewsService
    }
  }
}}
```

You can access the services as follows:

```js
cds.env.requires.db              //> the effective config for db
cds.env.requires.reviews         //> the effective config for reviews
cds.env.requires.ReviewsService  //> undefined
```

```js
cds.requires.db                  //> the effective config for db
cds.requires.reviews             //> the effective config for reviews
cds.requires.ReviewsService      //> same as above
```

The additional entries are useful for code that needs to securely access the service by cds definition name.

Note: as `cds.requires` is an overlay to `cds.env.requires`, it inherits all properties from there via prototype chain. In effect using operations which only look at *own* properties, like behave different than `cds.env.requires:

```js
Object.keys(cds.env.requires) //> [ 'db', 'reviews' ]
Object.keys(cds.env.requires) //> [ 'ReviewsService' ]
```

**Comment by renejeglinsky** [comment]
The improved documentation is now published. Thanks!
