### ISSUE TITLE
Add documentation how to add headers to response

### ISSUE THREAD

**Issue by sebastianesch** [cap-js/docs#687]
Hi,

it would be nice to explain in https://github.com/cap-js/docs/blob/main/node.js/events.md#class-cdsrequest--cds-request-, how to return custom response headers.

I think the correct way would be using `req.res.setHeader()`, but I think from the past, there are a lot of examples in the wild, that use private APIs like e.g. https://community.sap.com/t5/technology-q-a/how-to-add-header-in-cap-service-response/qaq-p/12674871#M4755468 or here https://community.sap.com/t5/technology-q-a/add-response-headers-in-sap-cap/qaq-p/12644749#M4743715.

Kind regards,
Sebastian

**Comment by renejeglinsky** [comment]
Hi Sebastian,
thanks for opening this issue. This topic is in the backlog in conjunction with a planned development in that area. Will update you here when we can provide more information.
All the best,
René

**Comment by sjvans** [comment]
should be ok with the current state (although i can't remember if i modified it or not ^^):

![Screenshot 2024-10-29 at 20 24 58](https://github.com/user-attachments/assets/14dd4d08-09e6-4080-a8e4-83fc0620a810)

hence, i'll close this one. please object if necessary.

best,
sebastian
