### ISSUE TITLE
Event Mesh -- Queue not created (package.json does not work as described) 

### ISSUE THREAD

**Issue by jankrieg** [cap-js/docs#705]
Hi guys,

I deployed a node app (no errors). The deployment created an instance of the event mesh as expected (I see the client in the SAP Event MeshApp). Due to your documentation I added the definition of a queue to package.json:

```
  "cds": {
    "requires": {
      "[production]": {
        "auth": "xsuaa",
        "messaging": {
          "kind": "enterprise-messaging",
          "publishPrefix": "$namespace/",
          "subscribePrefix": "$namespace/",
           "queue": { "name": "$namespace/my/first/queue" }
        }
```
I can't see the queue: 

![image](https://github.com/cap-js/docs/assets/45254847/6221eac3-0c33-40be-a4fd-dd5d6d18c670)

I created an event and an action in the service cds:

```
    action raiseEvent();

    event NewEmployeeHired {
        employeeId   : Integer;
        employeeName : String;
        department   : String;
        hireDate     : Date;
    }
```

When the action is executed I emit the event:

```
 const messaging = await cds.connect.to('messaging');

 this.on("raiseEvent", async (req) => {
     await messaging.emit("NewEmployeeHired", {
        employeeId: 12345,
        employeeName: "Mickey",
        department: "Mouse",
        hireDate: new Date().toDateString(),
      });
    });
```

This seems to work (debugged this) but nothing happens (no event recorded on the BTP, no error raised). 
I followed your documentation on https://cap.cloud.sap/docs/guides/messaging/event-mesh. 

1. Why was the queue not created (package.json)?
2. Why does the "emit" work but nothing happens? (No event created on BTP)

Thanks,
Jan

**Comment by renejeglinsky** [comment]
Hi Jan,

I do understand your questions. Please raise this question in the [community](https://community.sap.com/t5/forums/postpage/choose-node/true/product-id/9f13aee1-834c-4105-8e43-ee442775e5ce/board-id/technology-questions) or create a [support ticket](https://cap.cloud.sap/docs/resources/#reporting-incidents).

This repo is solely for documentation contributions and fixes. We can't offer support here.

Thanks René
