### ISSUE TITLE
Community Plugins

### ISSUE THREAD

**Issue by vneecious** [cap-js/docs#709]
Recently, I've noticed a significant increase in the number of `cds-plugins` created by the community. However, these plugins often end up scattered across various places. It would be highly beneficial to create a new section dedicated solely to centralizing these plugins in one location. This would allow the entire community easy access to the developed plugins, greatly strengthening our ecosystem.

I envision something similar to what the [Nuxt team does with their modules](https://nuxt.com/modules). They have a designated repository for listing these plugins ([nuxt/modules](https://github.com/nuxt/modules)), where each module is represented by a `.yaml` file containing important information about it (npm, git repository, image, name, description, etc). With each update, a new deployment is made to an [npm package](https://www.npmjs.com/package/@nuxt/modules) that exclusively compiles a json containing all the `.yaml` files from the repository. This package is then used on the Nuxt website to display all the available modules in an organized manner. 

Does it make sense to include this within the official docs?

**Comment by renejeglinsky** [comment]
Hi @vneecious ,

thanks you for sharing this idea. When reading it I remembered a blog post I read some time ago: https://community.sap.com/t5/technology-blogs-by-members/best-of-cap-js-the-best-place-to-find-packages-for-the-sap-cap-ecosystem/ba-p/13581351

I think there is such a page as you described it but it's not part of the official documentation. And it probably shouldn't be as it's owned and driven by the community: https://bestofcapjs.org/#/packages?tokens=plugin:type


We could think about adding a link to our docs. This needs some legal clarification first but I'll follow up on this and let you know here (even if it's closed then).

For now I'll close this issue as it's initial idea is already out there :)

All the best,
René
