### ISSUE TITLE
In a Nutshell - Wrong sqlite name

### ISSUE THREAD

**Issue by cyb3rko** [cap-js/docs#739]
Hey guys.

When following the instructions and filling the `package.json` with the content shown below, the following sqlite database name is wrong. That's why the two sqlite3 commands don't deliver any results.

The sentence mentioning the filename and the two commands  
```
sqlite3 my.sqlite .dump
sqlite3 my.sqlite .tables
```

should be changed to `db.sqlite`.

<img width="1067" alt="Bildschirmfoto 2024-03-13 um 09 15 58" src="https://github.com/cap-js/docs/assets/46033730/c890fdc5-5ce0-448b-ab6c-71c56e0ad58d">

**Comment by swaldmann** [comment]
Hi @cyb3rko,

Thanks for the report, this is fixed with the linked PR. Will come with the next CAPire release.

Best regards,
Steffen
