### ISSUE TITLE
Update documentation: --output-file no longer supported in cds bind

### ISSUE THREAD

**Issue by AjitKP91** [cap-js/docs#803]
Documentation Link: [Hybrid Testing: With Profile and Output File](https://cap.cloud.sap/docs/advanced/hybrid-testing#with-profile-and-output-file)

--output-file no longer supported in cds bind and should be changed to --out

**Comment by renejeglinsky** [comment]
Hi @AjitKP91 ,
thanks for sharing your finding. I'll fix it.

All the best,
René
