### ISSUE TITLE
Confusing doco on @cap-js/notifications plugin - WorkZone or ANS?

### ISSUE THREAD

**Issue by js1972** [cap-js/docs#831]
The CAP documentation talks about this plugin (@cap-js/notifications) sending notifications/alerts via the Alert Notification Service. However, when I look at the npm package for the plugin (https://www.npmjs.com/package/@cap-js/notifications) it talks about using SAP Build Work Zone notifications.
The code and pre-requisites don't seem to work with ANS at all??

**Comment by renejeglinsky** [comment]
Hi @js1972 ,
thanks a lot for opening this issue. AFAIK the alert notifications service is used under the hood. If this implementation details leads to confusion, it's probably better to align with the readme of the plugin itself. @RamIndia do you agree?

**Comment by js1972** [comment]
But alerts can only be sent to work zone so it should be "marketed" / "documented" for work zone notifications only.
