### ISSUE TITLE
No documentation for where clause in cds.ql

### ISSUE THREAD

**Issue by sammok83** [cap-js/docs#856]
Looking at https://cap.cloud.sap/docs/node.js/cds-ql#where, there seems to be missing documentation for the where clause.
What I'm looking for:
e.g:
![image](https://github.com/cap-js/docs/assets/10509241/edbc21c8-fcd9-4dd3-a4fa-e2a601616096)

Current **where** doco:
![image](https://github.com/cap-js/docs/assets/10509241/676628cd-d07d-4808-9e9b-a750ba456dd6)

**Comment by nocin** [comment]
Hi @sammok83,

the content below `having()` is also valid for `where()`. Got also confused about this, the first time when looking at it.

Here it is the same but a bit more obvious: [https://cap.cloud.sap/docs/node.js/events#req-error](url)

BR,
Nico

**Comment by renejeglinsky** [comment]
Hi @sammok83 ,
yes, @nocin described it correctly. I agree, that we don't make it as clear here as it should be. I'll fix that.
All the best,
René

**Comment by renejeglinsky** [comment]
In addition we changed the styling, so that it's visually more clear:
![image](https://github.com/user-attachments/assets/2968050b-cbf6-41cb-ae86-6bad87d4a396)

(to be released most probably end of November)
