### ISSUE TITLE
cds bind: Combination of for and exec

### ISSUE THREAD

**Issue by IcyT** [cap-js/docs#864]
The documentation shows, that "--exec" and "--for" can be combined: https://cap.cloud.sap/docs/advanced/hybrid-testing#cds-bind-exec

When trying, I'm getting the following message:
"Parameter --for is not supported in combination with --exec. Its value will be ignored."

I am using @sap/cds-dk 7.8.2

**Comment by renejeglinsky** [comment]
Thanks @IcyT for reporting this. I'm on it and will get back to you.

Best,
René

**Comment by renejeglinsky** [comment]
Hi @IcyT ,

we fixed the documentation accordingly: https://github.com/cap-js/docs/pull/852/commits/eefd7cb285fb7b3450a4e8271ea05aa8dec11123

Thanks for opening this issue! :)

All the best,
René

**Comment by renejeglinsky** [comment]
Note: It's not yet published. It becomes publicly available with our next release.
