### ISSUE TITLE
CSRF Token on Batch Request not working (node.js/remote-services.md)

### ISSUE THREAD

**Issue by rocantonio** [cap-js/docs#915]
Trying the new configuration does not apply to Batch Requests:

` "API_PURCHASECONTRACT_PROCESS_SRV": {
            "credentials": {
                "destination": "CSD_SP_PPE_POA_CONTRACT_API"
            },
            "kind": "odata-v2",
            "model": "srv/external/API_PURCHASECONTRACT_PROCESS_SRV",
            "csrf": {
                "method": "get"
            },
            "csrfInBatch": true
        }`

![image](https://github.com/cap-js/docs/assets/13656734/fbd06bf0-23f6-4639-bbbe-e54b97da66a6)

**ERROR**
`"error" : {
    "code" : "/IWFND/CM_MGW/098",
    "message" : {
      "lang" : "en",
      "value" : "X-CSRF token is needed for Batch Processing with modifying operation"
    },`

Can you provide solution for this ?

**Comment by renejeglinsky** [comment]
Hi @rocantonio ,

This topic is marked as concept:
![image](https://github.com/cap-js/docs/assets/32062331/57011e28-f184-46f0-b382-7448c9d815a0)

So there's no solution to be provided as it's a topic that we're working on. Watch the release notes for more information. We'll roll out any new information there.

All the best,
René
