### ISSUE TITLE
handle multiple requests concurrently within a batch request 

### ISSUE THREAD

**Issue by Terry-Huang-00** [cap-js/docs#917]
Hi CAP team,
I am using CAP Java to develop my application. As we know that $batch request can contain multiple requests in the payload, and the service handler will handle the request one by one. Is there anyway to enable the parallel processing for the $batch request. Then I can handler the request in the service handler concurrently.

**Comment by renejeglinsky** [comment]
Hi @Terry-Huang-00 ,
we're using this repository only for documentation-related issues. Please use one of the channels mention in our ["Public Resources"](https://cap.cloud.sap/docs/resources/#public-resources) to ask your question. Remember: If asked on the community, other users can benefit as well :)

Thanks,
René

**Comment by Terry-Huang-00** [comment]
Yes, I already raised this question there? Do you know does anyone can add more hints there :)
https://community.sap.com/t5/technology-q-a/handle-multiple-requests-concurrently-within-a-batch-request/qaq-p/12763343

**Comment by Terry-Huang-00** [comment]
Looking forward the answers, we are really need it! Thanks.
