### ISSUE TITLE
Database deploy - Automatic schema evolution

### ISSUE THREAD

**Issue by federicobelotti** [cap-js/docs#922]
Hi all,
I faced a little problem while trying to take advantage of the automatic schema evolution within a PostgreSQL database (but the issue has been replicated with SQLite as well).
Months ago, whenever a change to the data model was made, while doing a `cds deploy` I could automatically have the changes reflected to the database schema without losing data without setting anything specific in the app configuration.
After upgrading the CDS libraries (`cds-js` as well as `cds-dk`) to the current version (7.9.X) I noticed that at each deploy, I kept losing the data since tables were dropped and created. Then I found out that the `cds_model` table has never been created since the first deployement, so no schema evolution was happening at all.
The [documentation regarding this topic](https://cap.cloud.sap/docs/guides/databases-postgres#schema-evolution) states you can have automatic schema evolution out-of-the-box and that, in order to not use it, you can disable it inside the `package.json`.
I actually had to do the opposite, which was to explicitly enable it through the `"schema_evolution": "auto"` parameter set in the `package.json` file. 

Checking the env data prior to enabling that setting, the `cds.requires.db.schema_evolution` variable value turned out to be `undefined`.

Is the documentation wrong or is the other way around and it is, in fact, a bug?

Thanks,
Federico

**Comment by renejeglinsky** [comment]
Hi @federicobelotti ,
Thank you. We're checking your issue and will get back to you.

All the best,
René

**Comment by federicobelotti** [comment]
Hello @patricebender,
I figured out what the problem is. In my application I use a `.cdsrc.json` file where I store credentials and other sensitive stuff. Inside the `package.json`, however, I do not use the `pg` profile, but the default one (I then don't specify any profile name inside the configuration). Unfortunately in this way is seems that the default values are not taken into account and they need to be explicitly defined.
For example, inside `package.json`:
```
  "cds": {
      "requires": {
          "db": {
              "dialect": "postgres",
              "impl": "@cap-js/postgres",
              "kind": "postgres"
          }
      }
  }
```

And in the `.cdsrc.json`:
```
"requires": {
    "db": {
        "credentials": {
            "host": "...",
            "port": 5432,
            "user": "postgres",
            "password": "...",
            "database": "..."
       },
    }
}
```

Inside the `package.json` file I have to also add `"schema_evolution": "auto"` in order to have it defined. Am I correct?

Thank you for your clarifications,
Federico
