### ISSUE TITLE
Update CAP documentation related java and sample code

### ISSUE THREAD

**Issue by mikolayek** [cap-js/docs#937]
I have tried to do step from documentation:

> Add a Sample CDS Model
>
> You can use the [CDS Maven plugin](https://cap.cloud.sap/docs/guides/developing-applications/building#cds-maven-plugin) to add a sample CDS model after creating your project. Navigate to the root folder of your CAP Java project and execute the following
> Maven command:
> 
> ```sh
> mvn com.sap.cds:cds-maven-plugin:addSample
> ```

but I got:

> [INFO] --- cds:2.9.1:addSample (default-cli) @ product-syndication-parent ---
> [WARNING]  Goal 'addSample' is deprecated: since 2.9.0. Use AddMojo with option -Dfeature=SAMPLE instead.

Can you update documenation to follow new approach of sample generation, please?

**Comment by renejeglinsky** [comment]
Hi @mikolayek ,
thank you for raising this issue. I'll get back to you soon.

All the best,
René

**Comment by renejeglinsky** [comment]
Hi @mikolayek 
This is going to be published to cap.cloud.sap with the next release. Probably by the end of the week. 

Thanks again!
