### ISSUE TITLE
OData Absolute Context URL is not working

### ISSUE THREAD

**Issue by Devmawi** [cap-js/docs#959]
I tried to configure an Absolute Context URL with the variable `cds.odata.contextAbsoluteUrl` for the `@odata.context` property as it is written in the documentation:
- https://cap.cloud.sap/docs/advanced/odata#absolute-context-url

But it has no effect. Then I have searched in the node module for the use of this variable `@sap/cds`, but it seems that this variable don't exists.

Content of `package.json`:

``` json
{
  "name": "ODataAbsoluteUrl",
  "version": "1.0.0",
  "description": "A simple CAP project.",
  "repository": "<Add your repository here>",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap/cds": "^7",
    "express": "^4",
    "@sap/cds-hana": "^2"
  },
  "devDependencies": {
    "@cap-js/sqlite": "^1",
    "@sap/eslint-plugin-cds": "^3",
    "eslint": "^9"
  },
  "scripts": {
    "start": "cds-serve"
  },
  "cds": {
    "requires": {
      "db": "hana"
    }
  }
}
```

Code for `server.js`:

``` javascript
const cds = require('@sap/cds')
cds.odata.contextAbsoluteUrl = "https://your.domain.com/yourService"
```

**Comment by Devmawi** [comment]
Hi @renejeglinsky,

the context urls are remaining in a relative form like `$metadata#Books` . I have created a very minimal example in SAP BAS: 
[ODataAbsoluteUrl.zip](https://github.com/cap-js/docs/files/15461320/ODataAbsoluteUrl.zip)

**Comment by renejeglinsky** [comment]
Thanks @Devmawi!

@David-Kunz Could you explain the situation experienced by @Devmawi ?

**Comment by Devmawi** [comment]
@David-Kunz: Any idea why the configuration explained, doesn't work?

**Comment by David-Kunz** [comment]
Hi @Devmawi ,

I just tried it out with `cds init --add tiny-samples` and added the configuration to the `package.json` file:

```json
{
 ...,
  "cds": {
    "odata": {
      "contextAbsoluteUrl": "http://www.foo.com"
    }
  }
}
```

and I correctly get

```
{
"value": [
{
"ID": 1,
"title": "Wuthering Heights",
"stock": 100
},
{
"ID": 2,
"title": "Jane Eyre",
"stock": 500
}
],
"@odata.context": "http://www.foo.com/$metadata#Books"
}
```

Could you also add it to the `package.json` file instead of doing it dynamically during runtime?

Thanks and best regards,
David

**Comment by chgeo** [comment]
No response - closing this one.
