### ISSUE TITLE
How should Customization of req.user work now?

### ISSUE THREAD

**Issue by biscimus** [cap-js/docs#963]
In the [customization of req.user](https://cap.cloud.sap/docs/node.js/cds-serve#customization-of-req-user) section, ``ctx_auth()`` is listed as a middleware function, but since the newer updates, it's gone. Is this feature just gone, or how should this be performed in the newer versions of CAP?

**Comment by renejeglinsky** [comment]
Hi @biscimus ,
The docs have been moved: https://cap.cloud.sap/docs/node.js/cds-serve#auth
This is what you mean, right?

**Comment by biscimus** [comment]
Yes, but `ctx_auth` seems to be deprecated now and everything is inside `auth`. However, according to the documentation, the user customization was only possible if we added a custom middleware between `ctx_auth` and `auth`. How should we now handle this issue with the newest version of CAP?

**Comment by renejeglinsky** [comment]
Watch out for the upcoming major. I was told this is solved then. I'll keep you posted.

**Comment by sjvans** [comment]
hi @biscimus 

we will update the docs soon (together with the release of cds 8), sorry for the confusion.

from cds 7.5 onwards, you can do the following:
```js
cds.middlewares.before = [
  cds.middlewares.context(),
  cds.middlewares.trace(),
  cds.middlewares.auth(),
  function ctx_user (req,res,next) {
    const ctx = cds.context
    ctx.user.id = '<my-idp>' + ctx.user.id
    next()
  },
  cds.middlewares.ctx_model(),
]
```

best,
sebastian

**Comment by chgeo** [comment]
@sjvans has this now been addressed with the docs for cds 8?
