### ISSUE TITLE
Update DB Schema in Combination with Blue-Green Deployment

### ISSUE THREAD

**Issue by nocin** [cap-js/docs#965]
Hi,

via https://github.com/cap-js/docs/issues/427 I found the new content related to DB schema updates.
In [this section](https://cap.cloud.sap/docs/guides/multitenancy/?impl-variant=node#cds-mtx-upgrade-command) are two new topics for me. First, that you can update the DB schema using `cds-mtx update`, and second, that you can combine this with Blue-Green Deployment. I have two question on that.

I would like to setup up Blue-Green Deployment for our Multitenant application, but we are not using a sidecar, means we are not using `cds-mtx`. 
> The command must be run in the MTX application / sidecar root directory with the application environment.

Does `cds-mtx update` work, when not having a sidecar?

And is there any more content related to CAP and Blue-Green Deployment?
The only post I found in this community is [this one](https://community.sap.com/t5/technology-q-a/how-to-handle-blue-green-deployment-of-sap-cap-applications/qaq-p/12466035), which raises the question, what happens if a DB model upgrade fails? Is there any rollback? From my understanding this is not possible, because the previous live version is deleted, when setting the idle version productive. 

It would really help, if the CAP docs can be enhanced on this topic.

Thanks!
Nico

**Comment by renejeglinsky** [comment]
Hi @nocin ,

Thanks for raising this question. I'll get back to you soon after reCAP.

**Comment by renejeglinsky** [comment]
Hi @nocin ,
I'm picking this up now and let you know about the progress.
Thanks,
René

**Comment by swaldmann** [comment]
Hi,

`cds-mtx` is part of `@sap/cds-mtxs` and can therefore only be used with the MTX sidecar.

CAP doesn't give any advice or best practices wrt. blue-green deployment as of now, but it might change once it's decided in our roadmap that it'll get a stronger focus.

Best regards,
Steffen

**Comment by renejeglinsky** [comment]
Hi @nocin ,
for now I can't close this request with a success message. But, please watch out in the release notes where we will mention if the documentation around this topic has been enhanced.

All the best,
René
