### ISSUE TITLE
Could we use `npm install -D ts-jest` instead of `npm add ts-jest`?

### ISSUE THREAD

**Issue by ziyang-works** [cap-js/docs#985]
Questions regarding https://cap.cloud.sap/docs/node.js/typescript#testing-with-ts-jest
<img width="710" alt="image" src="https://github.com/cap-js/docs/assets/152387247/e2b82996-6c82-4c8d-89e9-28d0e9d7e4db">

1. `npm add` is an alias for much more common `npm install` ([source](https://docs.npmjs.com/cli/v10/commands/npm-install)). Could we use the latter to avoid confusion?
2. `ts-jest` is a dev dependency, but `npm add` adds it to `dependencies`. We should use `npm install -D ts-jest` instead

**Comment by renejeglinsky** [comment]
Thank you for opening this issue and the corresponding PR.

All the best,
René
