### ISSUE TITLE
The runtime result does not meet expert documented result

### ISSUE THREAD

**Issue by nicuessa** [cap-js/docs#994]
In this chapter https://cap.cloud.sap/docs/java/reflection-api:
```
if (type.isSimple()) {   // true
  CdsSimpleType simple = type.as(CdsSimpleType.class);

  String typeName = simple.getQualifiedName();  // "cds.String"
  CdsBaseType baseType = simple.getType();      // CdsBaseType.STRING
  Class<?> javaType = simple.getJavaType();     // String.class
  **Boolean localized = simple.get("localized");  // true**
  Integer length = simple.get("length");        // 111
}
```

The actual value of `localized` is **null**.

In `com.sap.cds.reflect.impl.CdsSimpleTypeBuilder`, the property "localized" is not listed.
```
public <T> T get(String property) {
	switch (property) {
		case CdsConstants.LENGTH:
		case CdsConstants.PRECISION:
		case CdsConstants.SRID:
			return (T) Integer.valueOf(v1);
		default:
			return null;
	}
}
```

**Comment by beckermarc** [comment]
@agoerler and @MattSchur can you please take a look at that? I think you know this area better than me.

**Comment by MattSchur** [comment]
Thanks @nicuessa, localized is a property of the element `title` (in the example). The correct code is 
```java
CdsElement title = books.getElement("title");
boolean localized = title.isLocalized();
```
We will fix the documentation.

**Comment by renejeglinsky** [comment]
Thanks @MattSchur for providing the fix.
Thanks again @nicuessa for raising this issue :)
